// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/user.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	user "github.com/ilhammhdd/kudaki-item-review-service/entities/aggregates/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//user auth service commands
type UserAuthServiceCommandTopic int32

const (
	UserAuthServiceCommandTopic_SIGN_UP                   UserAuthServiceCommandTopic = 0
	UserAuthServiceCommandTopic_VERIFY_USER               UserAuthServiceCommandTopic = 1
	UserAuthServiceCommandTopic_LOGIN                     UserAuthServiceCommandTopic = 2
	UserAuthServiceCommandTopic_CHANGE_PASSWORD           UserAuthServiceCommandTopic = 3
	UserAuthServiceCommandTopic_SEND_RESET_PASSWORD_EMAIL UserAuthServiceCommandTopic = 4
	UserAuthServiceCommandTopic_RESET_PASSWORD            UserAuthServiceCommandTopic = 5
)

var UserAuthServiceCommandTopic_name = map[int32]string{
	0: "SIGN_UP",
	1: "VERIFY_USER",
	2: "LOGIN",
	3: "CHANGE_PASSWORD",
	4: "SEND_RESET_PASSWORD_EMAIL",
	5: "RESET_PASSWORD",
}

var UserAuthServiceCommandTopic_value = map[string]int32{
	"SIGN_UP":                   0,
	"VERIFY_USER":               1,
	"LOGIN":                     2,
	"CHANGE_PASSWORD":           3,
	"SEND_RESET_PASSWORD_EMAIL": 4,
	"RESET_PASSWORD":            5,
}

func (x UserAuthServiceCommandTopic) String() string {
	return proto.EnumName(UserAuthServiceCommandTopic_name, int32(x))
}

func (UserAuthServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{0}
}

//
//user auth service events
type UserAuthServiceEventTopic int32

const (
	UserAuthServiceEventTopic_SIGNED_UP                    UserAuthServiceEventTopic = 0
	UserAuthServiceEventTopic_USER_VERIFIED                UserAuthServiceEventTopic = 1
	UserAuthServiceEventTopic_LOGGEDIN                     UserAuthServiceEventTopic = 2
	UserAuthServiceEventTopic_PASSWORD_CHANGED             UserAuthServiceEventTopic = 3
	UserAuthServiceEventTopic_RESET_PASSWORD_EMAIL_SENT    UserAuthServiceEventTopic = 4
	UserAuthServiceEventTopic_PASSWORD_RESETED             UserAuthServiceEventTopic = 5
	UserAuthServiceEventTopic_USER_VERIFICATION_EMAIL_SENT UserAuthServiceEventTopic = 6
)

var UserAuthServiceEventTopic_name = map[int32]string{
	0: "SIGNED_UP",
	1: "USER_VERIFIED",
	2: "LOGGEDIN",
	3: "PASSWORD_CHANGED",
	4: "RESET_PASSWORD_EMAIL_SENT",
	5: "PASSWORD_RESETED",
	6: "USER_VERIFICATION_EMAIL_SENT",
}

var UserAuthServiceEventTopic_value = map[string]int32{
	"SIGNED_UP":                    0,
	"USER_VERIFIED":                1,
	"LOGGEDIN":                     2,
	"PASSWORD_CHANGED":             3,
	"RESET_PASSWORD_EMAIL_SENT":    4,
	"PASSWORD_RESETED":             5,
	"USER_VERIFICATION_EMAIL_SENT": 6,
}

func (x UserAuthServiceEventTopic) String() string {
	return proto.EnumName(UserAuthServiceEventTopic_name, int32(x))
}

func (UserAuthServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{1}
}

//
//user info service commands
type UserInfoServiceCommandTopic int32

const (
	UserInfoServiceCommandTopic_ADD_ADDRESS        UserInfoServiceCommandTopic = 0
	UserInfoServiceCommandTopic_UPDATE_ADDRESS     UserInfoServiceCommandTopic = 1
	UserInfoServiceCommandTopic_UPDATE_PROFILE     UserInfoServiceCommandTopic = 2
	UserInfoServiceCommandTopic_RETRIEVE_ADDRESSES UserInfoServiceCommandTopic = 3
)

var UserInfoServiceCommandTopic_name = map[int32]string{
	0: "ADD_ADDRESS",
	1: "UPDATE_ADDRESS",
	2: "UPDATE_PROFILE",
	3: "RETRIEVE_ADDRESSES",
}

var UserInfoServiceCommandTopic_value = map[string]int32{
	"ADD_ADDRESS":        0,
	"UPDATE_ADDRESS":     1,
	"UPDATE_PROFILE":     2,
	"RETRIEVE_ADDRESSES": 3,
}

func (x UserInfoServiceCommandTopic) String() string {
	return proto.EnumName(UserInfoServiceCommandTopic_name, int32(x))
}

func (UserInfoServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{2}
}

//
//user info service events
type UserInfoServiceEventTopic int32

const (
	UserInfoServiceEventTopic_ADDRESS_ADDED       UserInfoServiceEventTopic = 0
	UserInfoServiceEventTopic_ADDRESS_UPDATED     UserInfoServiceEventTopic = 1
	UserInfoServiceEventTopic_PROFILE_UPDATED     UserInfoServiceEventTopic = 2
	UserInfoServiceEventTopic_ADDRESSES_RETRIEVED UserInfoServiceEventTopic = 3
)

var UserInfoServiceEventTopic_name = map[int32]string{
	0: "ADDRESS_ADDED",
	1: "ADDRESS_UPDATED",
	2: "PROFILE_UPDATED",
	3: "ADDRESSES_RETRIEVED",
}

var UserInfoServiceEventTopic_value = map[string]int32{
	"ADDRESS_ADDED":       0,
	"ADDRESS_UPDATED":     1,
	"PROFILE_UPDATED":     2,
	"ADDRESSES_RETRIEVED": 3,
}

func (x UserInfoServiceEventTopic) String() string {
	return proto.EnumName(UserInfoServiceEventTopic_name, int32(x))
}

func (UserInfoServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{3}
}

type Signup struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Photo                string   `protobuf:"bytes,7,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signup) Reset()         { *m = Signup{} }
func (m *Signup) String() string { return proto.CompactTextString(m) }
func (*Signup) ProtoMessage()    {}
func (*Signup) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{0}
}

func (m *Signup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signup.Unmarshal(m, b)
}
func (m *Signup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signup.Marshal(b, m, deterministic)
}
func (m *Signup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signup.Merge(m, src)
}
func (m *Signup) XXX_Size() int {
	return xxx_messageInfo_Signup.Size(m)
}
func (m *Signup) XXX_DiscardUnknown() {
	xxx_messageInfo_Signup.DiscardUnknown(m)
}

var xxx_messageInfo_Signup proto.InternalMessageInfo

func (m *Signup) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Signup) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Signup) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Signup) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Signup) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Signup) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Signup) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

type VerifyUser struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	VerifyToken          string   `protobuf:"bytes,2,opt,name=verify_token,json=verifyToken,proto3" json:"verify_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUser) Reset()         { *m = VerifyUser{} }
func (m *VerifyUser) String() string { return proto.CompactTextString(m) }
func (*VerifyUser) ProtoMessage()    {}
func (*VerifyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{1}
}

func (m *VerifyUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUser.Unmarshal(m, b)
}
func (m *VerifyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUser.Marshal(b, m, deterministic)
}
func (m *VerifyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUser.Merge(m, src)
}
func (m *VerifyUser) XXX_Size() int {
	return xxx_messageInfo_VerifyUser.Size(m)
}
func (m *VerifyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUser.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUser proto.InternalMessageInfo

func (m *VerifyUser) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *VerifyUser) GetVerifyToken() string {
	if m != nil {
		return m.VerifyToken
	}
	return ""
}

type Login struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{2}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Login) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChangePassword struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	OldPassword          string   `protobuf:"bytes,4,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePassword) Reset()         { *m = ChangePassword{} }
func (m *ChangePassword) String() string { return proto.CompactTextString(m) }
func (*ChangePassword) ProtoMessage()    {}
func (*ChangePassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{3}
}

func (m *ChangePassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePassword.Unmarshal(m, b)
}
func (m *ChangePassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePassword.Marshal(b, m, deterministic)
}
func (m *ChangePassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePassword.Merge(m, src)
}
func (m *ChangePassword) XXX_Size() int {
	return xxx_messageInfo_ChangePassword.Size(m)
}
func (m *ChangePassword) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePassword.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePassword proto.InternalMessageInfo

func (m *ChangePassword) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ChangePassword) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *ChangePassword) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePassword) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

type SendResetPasswordEmail struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResetPasswordEmail) Reset()         { *m = SendResetPasswordEmail{} }
func (m *SendResetPasswordEmail) String() string { return proto.CompactTextString(m) }
func (*SendResetPasswordEmail) ProtoMessage()    {}
func (*SendResetPasswordEmail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{4}
}

func (m *SendResetPasswordEmail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResetPasswordEmail.Unmarshal(m, b)
}
func (m *SendResetPasswordEmail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResetPasswordEmail.Marshal(b, m, deterministic)
}
func (m *SendResetPasswordEmail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResetPasswordEmail.Merge(m, src)
}
func (m *SendResetPasswordEmail) XXX_Size() int {
	return xxx_messageInfo_SendResetPasswordEmail.Size(m)
}
func (m *SendResetPasswordEmail) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResetPasswordEmail.DiscardUnknown(m)
}

var xxx_messageInfo_SendResetPasswordEmail proto.InternalMessageInfo

func (m *SendResetPasswordEmail) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SendResetPasswordEmail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResetPassword struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ResetToken           string   `protobuf:"bytes,2,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPassword) Reset()         { *m = ResetPassword{} }
func (m *ResetPassword) String() string { return proto.CompactTextString(m) }
func (*ResetPassword) ProtoMessage()    {}
func (*ResetPassword) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{5}
}

func (m *ResetPassword) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPassword.Unmarshal(m, b)
}
func (m *ResetPassword) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPassword.Marshal(b, m, deterministic)
}
func (m *ResetPassword) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPassword.Merge(m, src)
}
func (m *ResetPassword) XXX_Size() int {
	return xxx_messageInfo_ResetPassword.Size(m)
}
func (m *ResetPassword) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPassword.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPassword proto.InternalMessageInfo

func (m *ResetPassword) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResetPassword) GetResetToken() string {
	if m != nil {
		return m.ResetToken
	}
	return ""
}

func (m *ResetPassword) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type Signedup struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus          *Status       `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Profile              *user.Profile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Signup               *Signup       `protobuf:"bytes,4,opt,name=signup,proto3" json:"signup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Signedup) Reset()         { *m = Signedup{} }
func (m *Signedup) String() string { return proto.CompactTextString(m) }
func (*Signedup) ProtoMessage()    {}
func (*Signedup) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{6}
}

func (m *Signedup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signedup.Unmarshal(m, b)
}
func (m *Signedup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signedup.Marshal(b, m, deterministic)
}
func (m *Signedup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signedup.Merge(m, src)
}
func (m *Signedup) XXX_Size() int {
	return xxx_messageInfo_Signedup.Size(m)
}
func (m *Signedup) XXX_DiscardUnknown() {
	xxx_messageInfo_Signedup.DiscardUnknown(m)
}

var xxx_messageInfo_Signedup proto.InternalMessageInfo

func (m *Signedup) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Signedup) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *Signedup) GetProfile() *user.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Signedup) GetSignup() *Signup {
	if m != nil {
		return m.Signup
	}
	return nil
}

type UserVerified struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus          *Status     `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	User                 *user.User  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	VerifyUser           *VerifyUser `protobuf:"bytes,4,opt,name=verify_user,json=verifyUser,proto3" json:"verify_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserVerified) Reset()         { *m = UserVerified{} }
func (m *UserVerified) String() string { return proto.CompactTextString(m) }
func (*UserVerified) ProtoMessage()    {}
func (*UserVerified) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{7}
}

func (m *UserVerified) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerified.Unmarshal(m, b)
}
func (m *UserVerified) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerified.Marshal(b, m, deterministic)
}
func (m *UserVerified) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerified.Merge(m, src)
}
func (m *UserVerified) XXX_Size() int {
	return xxx_messageInfo_UserVerified.Size(m)
}
func (m *UserVerified) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerified.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerified proto.InternalMessageInfo

func (m *UserVerified) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserVerified) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *UserVerified) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserVerified) GetVerifyUser() *VerifyUser {
	if m != nil {
		return m.VerifyUser
	}
	return nil
}

type Loggedin struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus          *Status    `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	User                 *user.User `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Login                *Login     `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Loggedin) Reset()         { *m = Loggedin{} }
func (m *Loggedin) String() string { return proto.CompactTextString(m) }
func (*Loggedin) ProtoMessage()    {}
func (*Loggedin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{8}
}

func (m *Loggedin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loggedin.Unmarshal(m, b)
}
func (m *Loggedin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loggedin.Marshal(b, m, deterministic)
}
func (m *Loggedin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loggedin.Merge(m, src)
}
func (m *Loggedin) XXX_Size() int {
	return xxx_messageInfo_Loggedin.Size(m)
}
func (m *Loggedin) XXX_DiscardUnknown() {
	xxx_messageInfo_Loggedin.DiscardUnknown(m)
}

var xxx_messageInfo_Loggedin proto.InternalMessageInfo

func (m *Loggedin) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Loggedin) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *Loggedin) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Loggedin) GetLogin() *Login {
	if m != nil {
		return m.Login
	}
	return nil
}

type PasswordChanged struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus          *Status         `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	User                 *user.User      `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	ChangePassword       *ChangePassword `protobuf:"bytes,4,opt,name=change_password,json=changePassword,proto3" json:"change_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PasswordChanged) Reset()         { *m = PasswordChanged{} }
func (m *PasswordChanged) String() string { return proto.CompactTextString(m) }
func (*PasswordChanged) ProtoMessage()    {}
func (*PasswordChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{9}
}

func (m *PasswordChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordChanged.Unmarshal(m, b)
}
func (m *PasswordChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordChanged.Marshal(b, m, deterministic)
}
func (m *PasswordChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordChanged.Merge(m, src)
}
func (m *PasswordChanged) XXX_Size() int {
	return xxx_messageInfo_PasswordChanged.Size(m)
}
func (m *PasswordChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordChanged.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordChanged proto.InternalMessageInfo

func (m *PasswordChanged) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PasswordChanged) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *PasswordChanged) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PasswordChanged) GetChangePassword() *ChangePassword {
	if m != nil {
		return m.ChangePassword
	}
	return nil
}

type ResetPasswordEmailSent struct {
	Uid                    string                  `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                   *user.User              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	RestToken              string                  `protobuf:"bytes,3,opt,name=rest_token,json=restToken,proto3" json:"rest_token,omitempty"`
	EventStatus            *Status                 `protobuf:"bytes,4,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	SendResetPasswordEmail *SendResetPasswordEmail `protobuf:"bytes,5,opt,name=sendReset_password_email,json=sendResetPasswordEmail,proto3" json:"sendReset_password_email,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *ResetPasswordEmailSent) Reset()         { *m = ResetPasswordEmailSent{} }
func (m *ResetPasswordEmailSent) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordEmailSent) ProtoMessage()    {}
func (*ResetPasswordEmailSent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{10}
}

func (m *ResetPasswordEmailSent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordEmailSent.Unmarshal(m, b)
}
func (m *ResetPasswordEmailSent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordEmailSent.Marshal(b, m, deterministic)
}
func (m *ResetPasswordEmailSent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordEmailSent.Merge(m, src)
}
func (m *ResetPasswordEmailSent) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordEmailSent.Size(m)
}
func (m *ResetPasswordEmailSent) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordEmailSent.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordEmailSent proto.InternalMessageInfo

func (m *ResetPasswordEmailSent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ResetPasswordEmailSent) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResetPasswordEmailSent) GetRestToken() string {
	if m != nil {
		return m.RestToken
	}
	return ""
}

func (m *ResetPasswordEmailSent) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ResetPasswordEmailSent) GetSendResetPasswordEmail() *SendResetPasswordEmail {
	if m != nil {
		return m.SendResetPasswordEmail
	}
	return nil
}

type PasswordReseted struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 *user.User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	EventStatus          *Status        `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	ResetPassword        *ResetPassword `protobuf:"bytes,4,opt,name=reset_password,json=resetPassword,proto3" json:"reset_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PasswordReseted) Reset()         { *m = PasswordReseted{} }
func (m *PasswordReseted) String() string { return proto.CompactTextString(m) }
func (*PasswordReseted) ProtoMessage()    {}
func (*PasswordReseted) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{11}
}

func (m *PasswordReseted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordReseted.Unmarshal(m, b)
}
func (m *PasswordReseted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordReseted.Marshal(b, m, deterministic)
}
func (m *PasswordReseted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordReseted.Merge(m, src)
}
func (m *PasswordReseted) XXX_Size() int {
	return xxx_messageInfo_PasswordReseted.Size(m)
}
func (m *PasswordReseted) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordReseted.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordReseted proto.InternalMessageInfo

func (m *PasswordReseted) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PasswordReseted) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PasswordReseted) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *PasswordReseted) GetResetPassword() *ResetPassword {
	if m != nil {
		return m.ResetPassword
	}
	return nil
}

type UserVerificationEmailSent struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus          *Status    `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	User                 *user.User `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	VerifyToken          string     `protobuf:"bytes,4,opt,name=verify_token,json=verifyToken,proto3" json:"verify_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserVerificationEmailSent) Reset()         { *m = UserVerificationEmailSent{} }
func (m *UserVerificationEmailSent) String() string { return proto.CompactTextString(m) }
func (*UserVerificationEmailSent) ProtoMessage()    {}
func (*UserVerificationEmailSent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{12}
}

func (m *UserVerificationEmailSent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVerificationEmailSent.Unmarshal(m, b)
}
func (m *UserVerificationEmailSent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVerificationEmailSent.Marshal(b, m, deterministic)
}
func (m *UserVerificationEmailSent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVerificationEmailSent.Merge(m, src)
}
func (m *UserVerificationEmailSent) XXX_Size() int {
	return xxx_messageInfo_UserVerificationEmailSent.Size(m)
}
func (m *UserVerificationEmailSent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVerificationEmailSent.DiscardUnknown(m)
}

var xxx_messageInfo_UserVerificationEmailSent proto.InternalMessageInfo

func (m *UserVerificationEmailSent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserVerificationEmailSent) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *UserVerificationEmailSent) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserVerificationEmailSent) GetVerifyToken() string {
	if m != nil {
		return m.VerifyToken
	}
	return ""
}

type AddAddress struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	ReceiverName         string   `protobuf:"bytes,3,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	FullAddress          string   `protobuf:"bytes,4,opt,name=full_address,json=fullAddress,proto3" json:"full_address,omitempty"`
	ReceiverPhoneNumber  string   `protobuf:"bytes,5,opt,name=receiver_phone_number,json=receiverPhoneNumber,proto3" json:"receiver_phone_number,omitempty"`
	Latitude             float32  `protobuf:"fixed32,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ZipCode              string   `protobuf:"bytes,8,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAddress) Reset()         { *m = AddAddress{} }
func (m *AddAddress) String() string { return proto.CompactTextString(m) }
func (*AddAddress) ProtoMessage()    {}
func (*AddAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{13}
}

func (m *AddAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAddress.Unmarshal(m, b)
}
func (m *AddAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAddress.Marshal(b, m, deterministic)
}
func (m *AddAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAddress.Merge(m, src)
}
func (m *AddAddress) XXX_Size() int {
	return xxx_messageInfo_AddAddress.Size(m)
}
func (m *AddAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAddress.DiscardUnknown(m)
}

var xxx_messageInfo_AddAddress proto.InternalMessageInfo

func (m *AddAddress) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddAddress) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *AddAddress) GetReceiverName() string {
	if m != nil {
		return m.ReceiverName
	}
	return ""
}

func (m *AddAddress) GetFullAddress() string {
	if m != nil {
		return m.FullAddress
	}
	return ""
}

func (m *AddAddress) GetReceiverPhoneNumber() string {
	if m != nil {
		return m.ReceiverPhoneNumber
	}
	return ""
}

func (m *AddAddress) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *AddAddress) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *AddAddress) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

type UpdateAddress struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	FullAddress          string   `protobuf:"bytes,3,opt,name=full_address,json=fullAddress,proto3" json:"full_address,omitempty"`
	ReceiverName         string   `protobuf:"bytes,4,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhoneNumber  string   `protobuf:"bytes,5,opt,name=receiver_phone_number,json=receiverPhoneNumber,proto3" json:"receiver_phone_number,omitempty"`
	ZipCode              string   `protobuf:"bytes,6,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Latitude             float32  `protobuf:"fixed32,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AddressUuid          string   `protobuf:"bytes,9,opt,name=address_uuid,json=addressUuid,proto3" json:"address_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAddress) Reset()         { *m = UpdateAddress{} }
func (m *UpdateAddress) String() string { return proto.CompactTextString(m) }
func (*UpdateAddress) ProtoMessage()    {}
func (*UpdateAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{14}
}

func (m *UpdateAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAddress.Unmarshal(m, b)
}
func (m *UpdateAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAddress.Marshal(b, m, deterministic)
}
func (m *UpdateAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAddress.Merge(m, src)
}
func (m *UpdateAddress) XXX_Size() int {
	return xxx_messageInfo_UpdateAddress.Size(m)
}
func (m *UpdateAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAddress.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAddress proto.InternalMessageInfo

func (m *UpdateAddress) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateAddress) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *UpdateAddress) GetFullAddress() string {
	if m != nil {
		return m.FullAddress
	}
	return ""
}

func (m *UpdateAddress) GetReceiverName() string {
	if m != nil {
		return m.ReceiverName
	}
	return ""
}

func (m *UpdateAddress) GetReceiverPhoneNumber() string {
	if m != nil {
		return m.ReceiverPhoneNumber
	}
	return ""
}

func (m *UpdateAddress) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *UpdateAddress) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UpdateAddress) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *UpdateAddress) GetAddressUuid() string {
	if m != nil {
		return m.AddressUuid
	}
	return ""
}

type UpdateProfile struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Photo                string   `protobuf:"bytes,2,opt,name=photo,proto3" json:"photo,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	KudakiToken          string   `protobuf:"bytes,4,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfile) Reset()         { *m = UpdateProfile{} }
func (m *UpdateProfile) String() string { return proto.CompactTextString(m) }
func (*UpdateProfile) ProtoMessage()    {}
func (*UpdateProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{15}
}

func (m *UpdateProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfile.Unmarshal(m, b)
}
func (m *UpdateProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfile.Marshal(b, m, deterministic)
}
func (m *UpdateProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfile.Merge(m, src)
}
func (m *UpdateProfile) XXX_Size() int {
	return xxx_messageInfo_UpdateProfile.Size(m)
}
func (m *UpdateProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfile proto.InternalMessageInfo

func (m *UpdateProfile) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateProfile) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *UpdateProfile) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UpdateProfile) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

type RetrieveAddresses struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	ResultSchema         []byte   `protobuf:"bytes,3,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveAddresses) Reset()         { *m = RetrieveAddresses{} }
func (m *RetrieveAddresses) String() string { return proto.CompactTextString(m) }
func (*RetrieveAddresses) ProtoMessage()    {}
func (*RetrieveAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{16}
}

func (m *RetrieveAddresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveAddresses.Unmarshal(m, b)
}
func (m *RetrieveAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveAddresses.Marshal(b, m, deterministic)
}
func (m *RetrieveAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveAddresses.Merge(m, src)
}
func (m *RetrieveAddresses) XXX_Size() int {
	return xxx_messageInfo_RetrieveAddresses.Size(m)
}
func (m *RetrieveAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveAddresses proto.InternalMessageInfo

func (m *RetrieveAddresses) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveAddresses) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveAddresses) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type AddressAdded struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 *user.User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	EventStatus          *Status       `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	UsersAddress         *user.Address `protobuf:"bytes,5,opt,name=users_address,json=usersAddress,proto3" json:"users_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddressAdded) Reset()         { *m = AddressAdded{} }
func (m *AddressAdded) String() string { return proto.CompactTextString(m) }
func (*AddressAdded) ProtoMessage()    {}
func (*AddressAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{17}
}

func (m *AddressAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressAdded.Unmarshal(m, b)
}
func (m *AddressAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressAdded.Marshal(b, m, deterministic)
}
func (m *AddressAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressAdded.Merge(m, src)
}
func (m *AddressAdded) XXX_Size() int {
	return xxx_messageInfo_AddressAdded.Size(m)
}
func (m *AddressAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressAdded.DiscardUnknown(m)
}

var xxx_messageInfo_AddressAdded proto.InternalMessageInfo

func (m *AddressAdded) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddressAdded) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddressAdded) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *AddressAdded) GetUsersAddress() *user.Address {
	if m != nil {
		return m.UsersAddress
	}
	return nil
}

type AddressUpdated struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 *user.User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	EventStatus          *Status        `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	AddressBefore        *user.Address  `protobuf:"bytes,4,opt,name=address_before,json=addressBefore,proto3" json:"address_before,omitempty"`
	AddressAfter         *user.Address  `protobuf:"bytes,5,opt,name=address_after,json=addressAfter,proto3" json:"address_after,omitempty"`
	UpdateAddress        *UpdateAddress `protobuf:"bytes,6,opt,name=update_address,json=updateAddress,proto3" json:"update_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressUpdated) Reset()         { *m = AddressUpdated{} }
func (m *AddressUpdated) String() string { return proto.CompactTextString(m) }
func (*AddressUpdated) ProtoMessage()    {}
func (*AddressUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{18}
}

func (m *AddressUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressUpdated.Unmarshal(m, b)
}
func (m *AddressUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressUpdated.Marshal(b, m, deterministic)
}
func (m *AddressUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressUpdated.Merge(m, src)
}
func (m *AddressUpdated) XXX_Size() int {
	return xxx_messageInfo_AddressUpdated.Size(m)
}
func (m *AddressUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_AddressUpdated proto.InternalMessageInfo

func (m *AddressUpdated) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddressUpdated) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddressUpdated) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *AddressUpdated) GetAddressBefore() *user.Address {
	if m != nil {
		return m.AddressBefore
	}
	return nil
}

func (m *AddressUpdated) GetAddressAfter() *user.Address {
	if m != nil {
		return m.AddressAfter
	}
	return nil
}

func (m *AddressUpdated) GetUpdateAddress() *UpdateAddress {
	if m != nil {
		return m.UpdateAddress
	}
	return nil
}

type ProfileUpdated struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 *user.User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	EventStatus          *Status        `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	ProfileBefore        *user.Profile  `protobuf:"bytes,4,opt,name=profile_before,json=profileBefore,proto3" json:"profile_before,omitempty"`
	ProfileAfter         *user.Profile  `protobuf:"bytes,5,opt,name=profile_after,json=profileAfter,proto3" json:"profile_after,omitempty"`
	UpdateProfile        *UpdateProfile `protobuf:"bytes,6,opt,name=update_profile,json=updateProfile,proto3" json:"update_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProfileUpdated) Reset()         { *m = ProfileUpdated{} }
func (m *ProfileUpdated) String() string { return proto.CompactTextString(m) }
func (*ProfileUpdated) ProtoMessage()    {}
func (*ProfileUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{19}
}

func (m *ProfileUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileUpdated.Unmarshal(m, b)
}
func (m *ProfileUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileUpdated.Marshal(b, m, deterministic)
}
func (m *ProfileUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileUpdated.Merge(m, src)
}
func (m *ProfileUpdated) XXX_Size() int {
	return xxx_messageInfo_ProfileUpdated.Size(m)
}
func (m *ProfileUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileUpdated proto.InternalMessageInfo

func (m *ProfileUpdated) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProfileUpdated) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ProfileUpdated) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *ProfileUpdated) GetProfileBefore() *user.Profile {
	if m != nil {
		return m.ProfileBefore
	}
	return nil
}

func (m *ProfileUpdated) GetProfileAfter() *user.Profile {
	if m != nil {
		return m.ProfileAfter
	}
	return nil
}

func (m *ProfileUpdated) GetUpdateProfile() *UpdateProfile {
	if m != nil {
		return m.UpdateProfile
	}
	return nil
}

type AddressesRetrieved struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 *user.User      `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	EventStatus          *Status         `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Result               []byte          `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Addresses            []*user.Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddressesRetrieved) Reset()         { *m = AddressesRetrieved{} }
func (m *AddressesRetrieved) String() string { return proto.CompactTextString(m) }
func (*AddressesRetrieved) ProtoMessage()    {}
func (*AddressesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16fa325116cd758, []int{20}
}

func (m *AddressesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressesRetrieved.Unmarshal(m, b)
}
func (m *AddressesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressesRetrieved.Marshal(b, m, deterministic)
}
func (m *AddressesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressesRetrieved.Merge(m, src)
}
func (m *AddressesRetrieved) XXX_Size() int {
	return xxx_messageInfo_AddressesRetrieved.Size(m)
}
func (m *AddressesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_AddressesRetrieved proto.InternalMessageInfo

func (m *AddressesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddressesRetrieved) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddressesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *AddressesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AddressesRetrieved) GetAddresses() []*user.Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterEnum("event.UserAuthServiceCommandTopic", UserAuthServiceCommandTopic_name, UserAuthServiceCommandTopic_value)
	proto.RegisterEnum("event.UserAuthServiceEventTopic", UserAuthServiceEventTopic_name, UserAuthServiceEventTopic_value)
	proto.RegisterEnum("event.UserInfoServiceCommandTopic", UserInfoServiceCommandTopic_name, UserInfoServiceCommandTopic_value)
	proto.RegisterEnum("event.UserInfoServiceEventTopic", UserInfoServiceEventTopic_name, UserInfoServiceEventTopic_value)
	proto.RegisterType((*Signup)(nil), "event.Signup")
	proto.RegisterType((*VerifyUser)(nil), "event.VerifyUser")
	proto.RegisterType((*Login)(nil), "event.Login")
	proto.RegisterType((*ChangePassword)(nil), "event.ChangePassword")
	proto.RegisterType((*SendResetPasswordEmail)(nil), "event.SendResetPasswordEmail")
	proto.RegisterType((*ResetPassword)(nil), "event.ResetPassword")
	proto.RegisterType((*Signedup)(nil), "event.Signedup")
	proto.RegisterType((*UserVerified)(nil), "event.UserVerified")
	proto.RegisterType((*Loggedin)(nil), "event.Loggedin")
	proto.RegisterType((*PasswordChanged)(nil), "event.PasswordChanged")
	proto.RegisterType((*ResetPasswordEmailSent)(nil), "event.ResetPasswordEmailSent")
	proto.RegisterType((*PasswordReseted)(nil), "event.PasswordReseted")
	proto.RegisterType((*UserVerificationEmailSent)(nil), "event.UserVerificationEmailSent")
	proto.RegisterType((*AddAddress)(nil), "event.AddAddress")
	proto.RegisterType((*UpdateAddress)(nil), "event.UpdateAddress")
	proto.RegisterType((*UpdateProfile)(nil), "event.UpdateProfile")
	proto.RegisterType((*RetrieveAddresses)(nil), "event.RetrieveAddresses")
	proto.RegisterType((*AddressAdded)(nil), "event.AddressAdded")
	proto.RegisterType((*AddressUpdated)(nil), "event.AddressUpdated")
	proto.RegisterType((*ProfileUpdated)(nil), "event.ProfileUpdated")
	proto.RegisterType((*AddressesRetrieved)(nil), "event.AddressesRetrieved")
}

func init() { proto.RegisterFile("events/user.proto", fileDescriptor_f16fa325116cd758) }

var fileDescriptor_f16fa325116cd758 = []byte{
	// 1401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x0e, 0xf5, 0x65, 0x69, 0x44, 0xd9, 0xf4, 0x3a, 0xf1, 0xab, 0x38, 0x31, 0xde, 0x98, 0x2f,
	0x5e, 0xa0, 0x35, 0x10, 0xbb, 0x70, 0x81, 0x5e, 0x8a, 0x36, 0x65, 0x4c, 0xc6, 0x15, 0xea, 0xca,
	0x02, 0x29, 0x27, 0x68, 0x2f, 0x04, 0x2d, 0xae, 0x25, 0x22, 0x12, 0xa9, 0xf2, 0x43, 0x46, 0xf3,
	0x17, 0x0a, 0xf4, 0xd0, 0x7b, 0x7f, 0x40, 0x0f, 0x3d, 0xf4, 0x52, 0xe4, 0x90, 0x02, 0xfd, 0x0f,
	0xfd, 0x41, 0x2d, 0xf6, 0x8b, 0x22, 0x25, 0xda, 0x4e, 0x93, 0xc6, 0xbd, 0x69, 0x9f, 0x99, 0xd9,
	0x79, 0xe6, 0xd9, 0x1d, 0xee, 0x40, 0xb0, 0x8e, 0x67, 0xd8, 0x8f, 0xa3, 0xfd, 0x24, 0xc2, 0xe1,
	0xde, 0x34, 0x0c, 0xe2, 0x00, 0x55, 0x29, 0xb4, 0xb5, 0xc1, 0x2d, 0x51, 0xec, 0xc4, 0x49, 0xc4,
	0x6c, 0x5b, 0x5b, 0xce, 0x70, 0x18, 0xe2, 0xa1, 0x13, 0x63, 0x16, 0x92, 0x89, 0xdb, 0xda, 0x5e,
	0xb4, 0x4d, 0xc3, 0xe0, 0xdc, 0x1b, 0xe3, 0xcb, 0xcc, 0x8e, 0xeb, 0x86, 0x38, 0xe2, 0x3b, 0xab,
	0xbf, 0x4a, 0x50, 0xb3, 0xbc, 0xa1, 0x9f, 0x4c, 0x91, 0x02, 0xe5, 0xc4, 0x73, 0xdb, 0xd2, 0x03,
	0xe9, 0xbd, 0x86, 0x49, 0x7e, 0xa2, 0x7b, 0xd0, 0x38, 0x4f, 0xc6, 0x63, 0xdb, 0x77, 0x26, 0xb8,
	0x5d, 0xa2, 0x78, 0x9d, 0x00, 0x5d, 0x67, 0x82, 0xd1, 0x0e, 0xc8, 0xd3, 0x51, 0xe0, 0x63, 0xdb,
	0x4f, 0x26, 0x67, 0x38, 0x6c, 0x97, 0xa9, 0xbd, 0x49, 0xb1, 0x2e, 0x85, 0xd0, 0x6d, 0xa8, 0xe2,
	0x89, 0xe3, 0x8d, 0xdb, 0x15, 0x6a, 0x63, 0x0b, 0xb4, 0x05, 0xf5, 0xa9, 0x13, 0x45, 0x17, 0x41,
	0xe8, 0xb6, 0xab, 0x6c, 0x53, 0xb1, 0x46, 0x08, 0x2a, 0x61, 0x30, 0xc6, 0xed, 0x1a, 0xc5, 0xe9,
	0x6f, 0xb2, 0xcb, 0x74, 0x14, 0xc4, 0x41, 0x7b, 0x85, 0xed, 0x42, 0x17, 0xaa, 0x06, 0xf0, 0x14,
	0x87, 0xde, 0xf9, 0xb7, 0xa7, 0x11, 0x0e, 0x0b, 0xb8, 0xef, 0x80, 0x3c, 0xa3, 0x76, 0x3b, 0x0e,
	0x9e, 0x63, 0x9f, 0xd3, 0x6f, 0x32, 0xac, 0x4f, 0x20, 0xf5, 0x0b, 0xa8, 0x1e, 0x07, 0x43, 0xcf,
	0x2f, 0x88, 0x4e, 0x99, 0x97, 0x2e, 0x63, 0x5e, 0xce, 0x33, 0x57, 0xbf, 0x93, 0x60, 0xf5, 0x70,
	0xe4, 0xf8, 0x43, 0xdc, 0x13, 0xc5, 0x14, 0x92, 0x7a, 0x9e, 0xb8, 0xce, 0x73, 0x2f, 0x4f, 0x8a,
	0x61, 0x94, 0x14, 0x71, 0xf1, 0xf1, 0x85, 0xbd, 0x90, 0xa7, 0xe9, 0xe3, 0x8b, 0x74, 0xdf, 0x1d,
	0x90, 0x83, 0xb1, 0x3b, 0x77, 0x61, 0xea, 0x36, 0x83, 0xb1, 0x2b, 0x5c, 0xd4, 0xcf, 0x60, 0xd3,
	0xc2, 0xbe, 0x6b, 0xe2, 0x08, 0xc7, 0x02, 0x34, 0x68, 0x0d, 0xaf, 0x59, 0xab, 0x8a, 0xa1, 0x95,
	0x8b, 0x2e, 0x08, 0xfc, 0x2f, 0x34, 0x43, 0xe2, 0x92, 0x2b, 0x06, 0x28, 0xf4, 0xba, 0xb5, 0xa8,
	0x3f, 0x49, 0x50, 0x27, 0xf7, 0x0f, 0xbb, 0x85, 0x37, 0xf0, 0x03, 0x90, 0x69, 0x3f, 0xd8, 0xac,
	0x1d, 0x68, 0x8e, 0xe6, 0x41, 0x6b, 0x8f, 0x82, 0x7b, 0x16, 0x05, 0xcd, 0x26, 0x5d, 0xb1, 0x05,
	0x3a, 0x80, 0x15, 0xde, 0x00, 0x34, 0x5d, 0xf3, 0xa0, 0xbd, 0x37, 0xef, 0x80, 0x3d, 0xda, 0x37,
	0x3d, 0x66, 0x37, 0x85, 0x23, 0xfa, 0x3f, 0xd4, 0x22, 0xda, 0x03, 0x54, 0xca, 0xcc, 0xfe, 0x14,
	0x34, 0xb9, 0x51, 0xfd, 0x45, 0x02, 0x99, 0xdc, 0x36, 0x7a, 0xef, 0x3c, 0xec, 0xfe, 0x23, 0x7c,
	0xdf, 0x87, 0x0a, 0x21, 0xc5, 0xc9, 0xde, 0x59, 0x22, 0x4b, 0x12, 0x9a, 0xd4, 0x05, 0x1d, 0x00,
	0xbf, 0xbe, 0x36, 0x8d, 0x60, 0x5c, 0xd7, 0xf9, 0xde, 0xf3, 0x66, 0x30, 0x61, 0x96, 0xfe, 0x56,
	0x7f, 0x94, 0xa0, 0x7e, 0x1c, 0x0c, 0x87, 0xd8, 0x2d, 0xbc, 0xe7, 0xef, 0x94, 0xaf, 0x0a, 0xd5,
	0x31, 0xe9, 0x2f, 0xce, 0x54, 0xe6, 0xbb, 0xd2, 0x9e, 0x33, 0x99, 0x49, 0xfd, 0x5d, 0x82, 0x35,
	0x71, 0x19, 0x58, 0xfb, 0xdc, 0xb8, 0xac, 0x9f, 0xc2, 0xda, 0x80, 0x66, 0xce, 0x77, 0x14, 0x89,
	0x62, 0xfb, 0xe7, 0xdb, 0xda, 0x5c, 0x1d, 0xe4, 0xd6, 0xea, 0x9f, 0x12, 0x6c, 0x2e, 0x37, 0x9a,
	0x85, 0xfd, 0xb8, 0xa0, 0x12, 0xc1, 0xab, 0x74, 0x3d, 0xaf, 0x6d, 0x20, 0xbd, 0x24, 0xba, 0x8b,
	0xf5, 0x4e, 0x83, 0x20, 0xac, 0xb9, 0x16, 0x35, 0xa9, 0x5c, 0xab, 0xc9, 0x33, 0x68, 0x47, 0xe2,
	0xa3, 0x90, 0xd6, 0x6a, 0xb3, 0xde, 0xaf, 0xd2, 0xe8, 0x6d, 0x11, 0x5d, 0xf8, 0xed, 0x30, 0x37,
	0xa3, 0x42, 0x5c, 0xfd, 0x2d, 0x73, 0x88, 0xd4, 0x5c, 0x78, 0x88, 0x7f, 0xa3, 0xf4, 0xc5, 0xda,
	0xca, 0xd7, 0xd6, 0xf6, 0x31, 0xac, 0x86, 0xb9, 0xba, 0xb8, 0x1e, 0xb7, 0x79, 0x4c, 0x8e, 0xb5,
	0xd9, 0x0a, 0xb3, 0x4b, 0xf5, 0x67, 0x09, 0xee, 0xce, 0x1b, 0x7b, 0xe0, 0xc4, 0x5e, 0xe0, 0x5f,
	0x75, 0x88, 0xef, 0xf4, 0x3a, 0x2e, 0x3e, 0x5c, 0x95, 0xe5, 0x87, 0xeb, 0x87, 0x12, 0x80, 0xe6,
	0xba, 0x1a, 0x7b, 0xc9, 0xdf, 0xec, 0x9d, 0xf9, 0x1f, 0xb4, 0x42, 0x3c, 0xc0, 0xde, 0x0c, 0x87,
	0xec, 0x7d, 0x67, 0x17, 0x4c, 0x16, 0xa0, 0x78, 0xe3, 0xe9, 0x00, 0xc0, 0x67, 0x06, 0xc1, 0x85,
	0x60, 0x22, 0xf9, 0x01, 0xdc, 0x49, 0xf7, 0xc9, 0xcd, 0x03, 0xec, 0x69, 0xdf, 0x10, 0xc6, 0x5e,
	0x66, 0x2e, 0xd8, 0x82, 0xfa, 0xd8, 0x89, 0xbd, 0x38, 0x71, 0xd9, 0x4b, 0x5f, 0x32, 0xd3, 0x35,
	0xba, 0x0f, 0x8d, 0x71, 0xe0, 0x0f, 0x99, 0x71, 0x85, 0x1a, 0xe7, 0x00, 0xba, 0x0b, 0xf5, 0x17,
	0xde, 0xd4, 0x1e, 0x04, 0x2e, 0x6e, 0xd7, 0x69, 0x82, 0x95, 0x17, 0xde, 0xf4, 0x30, 0x70, 0xb1,
	0xfa, 0xb2, 0x04, 0xad, 0xd3, 0xa9, 0xeb, 0xc4, 0xf8, 0xad, 0x74, 0x59, 0x2c, 0xb9, 0xbc, 0x5c,
	0xf2, 0x92, 0x74, 0x95, 0x02, 0xe9, 0xde, 0x44, 0x97, 0x6c, 0x75, 0xb5, 0x5c, 0x75, 0x39, 0xc9,
	0x56, 0xae, 0x92, 0xac, 0xbe, 0x28, 0xd9, 0x0e, 0xc8, 0xbc, 0x16, 0x3b, 0x21, 0x72, 0x34, 0x58,
	0x41, 0x1c, 0x3b, 0x4d, 0x3c, 0x57, 0xbd, 0x10, 0xca, 0xf1, 0x97, 0xb1, 0x78, 0x48, 0x60, 0x43,
	0x58, 0x29, 0x33, 0x84, 0xe5, 0x07, 0xc4, 0xf2, 0xf2, 0x80, 0x98, 0x13, 0xbb, 0xb2, 0x24, 0xb6,
	0x3a, 0x81, 0x75, 0x13, 0xc7, 0xa1, 0x87, 0x67, 0xe2, 0xd0, 0xf0, 0xdb, 0x5c, 0xe7, 0x28, 0x19,
	0xc7, 0x76, 0x34, 0x18, 0xe1, 0x89, 0x43, 0xd9, 0xc8, 0xe4, 0x4c, 0x08, 0x68, 0x51, 0x4c, 0x7d,
	0x25, 0x81, 0xcc, 0xf3, 0x68, 0xae, 0x7b, 0xf3, 0x1f, 0xa9, 0x4f, 0xa0, 0x45, 0x22, 0xa3, 0xf4,
	0x72, 0x55, 0x2f, 0x99, 0x50, 0x38, 0x49, 0x53, 0xa6, 0xee, 0x7c, 0xa5, 0xbe, 0x2a, 0xc1, 0x2a,
	0xff, 0xcd, 0x8e, 0xeb, 0xc6, 0x0b, 0x78, 0x04, 0xab, 0xe2, 0x2e, 0x9d, 0xe1, 0xf3, 0x20, 0xc4,
	0xfc, 0x2b, 0x7b, 0x79, 0x05, 0x2d, 0xee, 0xff, 0x98, 0xba, 0x13, 0x05, 0xc4, 0x06, 0xce, 0x79,
	0xcc, 0xbb, 0xe1, 0x4a, 0x05, 0xb8, 0xbb, 0x46, 0xbc, 0xc9, 0x57, 0x3e, 0xa1, 0x95, 0xa7, 0x0a,
	0xd6, 0x72, 0x5f, 0xf9, 0x5c, 0xff, 0x9b, 0xad, 0x24, 0xbb, 0xa4, 0xf2, 0xf1, 0x0b, 0xfe, 0xef,
	0xc9, 0xc7, 0x47, 0xce, 0xeb, 0xe4, 0x13, 0x23, 0x6a, 0x8b, 0xfb, 0xcf, 0xe5, 0x13, 0x1b, 0x5c,
	0x2d, 0x9f, 0x88, 0x97, 0xb9, 0xfb, 0xa2, 0x7c, 0x62, 0x44, 0x2e, 0x92, 0x2f, 0xcd, 0x9d, 0x64,
	0x97, 0xea, 0x1f, 0x12, 0xa0, 0xb4, 0x49, 0x45, 0xd7, 0xde, 0xb8, 0x84, 0x9b, 0x50, 0x63, 0x2d,
	0x4d, 0xa5, 0x93, 0x4d, 0xbe, 0x42, 0x1f, 0x41, 0xc3, 0x11, 0xe4, 0xda, 0xd5, 0x07, 0xe5, 0x2b,
	0x2f, 0xd5, 0xdc, 0x75, 0xf7, 0x7b, 0x09, 0xee, 0x11, 0x42, 0x5a, 0x12, 0x8f, 0x2c, 0x1c, 0xce,
	0xbc, 0x01, 0x3e, 0x0c, 0x26, 0x13, 0xc7, 0x77, 0xfb, 0xc1, 0xd4, 0x1b, 0xa0, 0x26, 0xac, 0x58,
	0x9d, 0xa3, 0xae, 0x7d, 0xda, 0x53, 0x6e, 0xa1, 0x35, 0x68, 0x3e, 0x35, 0xcc, 0xce, 0x93, 0xaf,
	0xec, 0x53, 0xcb, 0x30, 0x15, 0x09, 0x35, 0xa0, 0x7a, 0x7c, 0x72, 0xd4, 0xe9, 0x2a, 0x25, 0xb4,
	0x01, 0x6b, 0x87, 0x9f, 0x6b, 0xdd, 0x23, 0xc3, 0xee, 0x69, 0x96, 0xf5, 0xec, 0xc4, 0xd4, 0x95,
	0x32, 0xda, 0x86, 0xbb, 0x96, 0xd1, 0xd5, 0x6d, 0xd3, 0xb0, 0x8c, 0x7e, 0x6a, 0xb0, 0x8d, 0x2f,
	0xb5, 0xce, 0xb1, 0x52, 0x41, 0x08, 0x56, 0xf3, 0x16, 0xa5, 0xba, 0xfb, 0x92, 0xcf, 0x22, 0x19,
	0x42, 0x06, 0xa9, 0x9f, 0xd1, 0x69, 0x41, 0x83, 0xd0, 0x31, 0x74, 0x46, 0x68, 0x1d, 0x5a, 0x84,
	0x89, 0x4d, 0x59, 0x75, 0x0c, 0x5d, 0x91, 0x90, 0x0c, 0xf5, 0xe3, 0x93, 0xa3, 0x23, 0x43, 0xa7,
	0xac, 0x6e, 0x83, 0x92, 0x66, 0x65, 0xf4, 0x38, 0xad, 0x22, 0x46, 0xb6, 0x65, 0x74, 0xfb, 0x4a,
	0x25, 0x17, 0x44, 0xfd, 0x0c, 0x5d, 0xa9, 0xa2, 0x07, 0x70, 0x3f, 0x93, 0xeb, 0x50, 0xeb, 0x77,
	0x4e, 0xba, 0xd9, 0xb8, 0xda, 0xae, 0xcf, 0xa4, 0xec, 0xf8, 0xe7, 0x41, 0x91, 0x94, 0x6b, 0xd0,
	0xd4, 0x74, 0xdd, 0xd6, 0x74, 0xdd, 0x34, 0x2c, 0x4b, 0xb9, 0x45, 0xca, 0x3f, 0xed, 0xe9, 0x5a,
	0xdf, 0x48, 0x31, 0x29, 0x83, 0xf5, 0xcc, 0x93, 0x27, 0x9d, 0x63, 0x43, 0x29, 0xa1, 0x4d, 0x40,
	0xa6, 0xd1, 0x37, 0x3b, 0xc6, 0xd3, 0xd4, 0xd3, 0xb0, 0x94, 0xf2, 0xee, 0x37, 0x4c, 0xa9, 0x4c,
	0xbe, 0x8c, 0x52, 0xeb, 0xd0, 0xe2, 0xbe, 0x24, 0xc6, 0xd0, 0x95, 0x5b, 0xe4, 0x88, 0x04, 0xc4,
	0x72, 0x10, 0xbd, 0x36, 0x60, 0x8d, 0x67, 0x4a, 0xc1, 0x12, 0xfa, 0x0f, 0x6c, 0xa4, 0x89, 0x6c,
	0x91, 0x5b, 0x57, 0xca, 0x8f, 0xb5, 0xaf, 0x1f, 0x0d, 0xbd, 0x78, 0x94, 0x9c, 0xed, 0x0d, 0x82,
	0xc9, 0xbe, 0x37, 0x1e, 0x39, 0x93, 0xc9, 0xc8, 0x75, 0xf7, 0xd9, 0x53, 0xf4, 0xd0, 0x8b, 0xf1,
	0xe4, 0x61, 0x88, 0x67, 0x1e, 0xbe, 0x78, 0x18, 0x31, 0x4a, 0xfb, 0x49, 0x84, 0x07, 0x4e, 0x84,
	0xa3, 0x7d, 0xf6, 0xc7, 0xce, 0x59, 0x8d, 0xfe, 0xf1, 0xf2, 0xe1, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0xf7, 0xe0, 0xf9, 0x03, 0x12, 0x00, 0x00,
}
