// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aggregates/kudaki_event/doku_invoice.proto

package kudaki_event

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DokuInvoiceStatus int32

const (
	DokuInvoiceStatus_NEW     DokuInvoiceStatus = 0
	DokuInvoiceStatus_SUCCESS DokuInvoiceStatus = 1
	DokuInvoiceStatus_FAILED  DokuInvoiceStatus = 2
)

var DokuInvoiceStatus_name = map[int32]string{
	0: "NEW",
	1: "SUCCESS",
	2: "FAILED",
}

var DokuInvoiceStatus_value = map[string]int32{
	"NEW":     0,
	"SUCCESS": 1,
	"FAILED":  2,
}

func (x DokuInvoiceStatus) String() string {
	return proto.EnumName(DokuInvoiceStatus_name, int32(x))
}

func (DokuInvoiceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60136d5b6d0fd8b0, []int{0}
}

type DokuInvoice struct {
	Id                    int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                  string            `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	KudakiEventUuid       string            `protobuf:"bytes,3,opt,name=kudaki_event_uuid,json=kudakiEventUuid,proto3" json:"kudaki_event_uuid,omitempty"`
	Amount                float32           `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PurchaseAmount        float32           `protobuf:"fixed32,5,opt,name=purchase_amount,json=purchaseAmount,proto3" json:"purchase_amount,omitempty"`
	TransactionIdMerchant string            `protobuf:"bytes,6,opt,name=transaction_id_merchant,json=transactionIdMerchant,proto3" json:"transaction_id_merchant,omitempty"`
	Words                 string            `protobuf:"bytes,7,opt,name=words,proto3" json:"words,omitempty"`
	RequestDateTime       int64             `protobuf:"varint,8,opt,name=request_date_time,json=requestDateTime,proto3" json:"request_date_time,omitempty"`
	Currency              int32             `protobuf:"varint,9,opt,name=currency,proto3" json:"currency,omitempty"`
	PurchaseCurrency      int32             `protobuf:"varint,10,opt,name=purchase_currency,json=purchaseCurrency,proto3" json:"purchase_currency,omitempty"`
	SessionId             string            `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name                  string            `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Email                 string            `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	Basket                string            `protobuf:"bytes,14,opt,name=basket,proto3" json:"basket,omitempty"`
	DokuInvoiceStatus     DokuInvoiceStatus `protobuf:"varint,15,opt,name=doku_invoice_status,json=dokuInvoiceStatus,proto3,enum=aggregates.kudaki_event.DokuInvoiceStatus" json:"doku_invoice_status,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *DokuInvoice) Reset()         { *m = DokuInvoice{} }
func (m *DokuInvoice) String() string { return proto.CompactTextString(m) }
func (*DokuInvoice) ProtoMessage()    {}
func (*DokuInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_60136d5b6d0fd8b0, []int{0}
}

func (m *DokuInvoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DokuInvoice.Unmarshal(m, b)
}
func (m *DokuInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DokuInvoice.Marshal(b, m, deterministic)
}
func (m *DokuInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DokuInvoice.Merge(m, src)
}
func (m *DokuInvoice) XXX_Size() int {
	return xxx_messageInfo_DokuInvoice.Size(m)
}
func (m *DokuInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_DokuInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_DokuInvoice proto.InternalMessageInfo

func (m *DokuInvoice) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DokuInvoice) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DokuInvoice) GetKudakiEventUuid() string {
	if m != nil {
		return m.KudakiEventUuid
	}
	return ""
}

func (m *DokuInvoice) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DokuInvoice) GetPurchaseAmount() float32 {
	if m != nil {
		return m.PurchaseAmount
	}
	return 0
}

func (m *DokuInvoice) GetTransactionIdMerchant() string {
	if m != nil {
		return m.TransactionIdMerchant
	}
	return ""
}

func (m *DokuInvoice) GetWords() string {
	if m != nil {
		return m.Words
	}
	return ""
}

func (m *DokuInvoice) GetRequestDateTime() int64 {
	if m != nil {
		return m.RequestDateTime
	}
	return 0
}

func (m *DokuInvoice) GetCurrency() int32 {
	if m != nil {
		return m.Currency
	}
	return 0
}

func (m *DokuInvoice) GetPurchaseCurrency() int32 {
	if m != nil {
		return m.PurchaseCurrency
	}
	return 0
}

func (m *DokuInvoice) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *DokuInvoice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DokuInvoice) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DokuInvoice) GetBasket() string {
	if m != nil {
		return m.Basket
	}
	return ""
}

func (m *DokuInvoice) GetDokuInvoiceStatus() DokuInvoiceStatus {
	if m != nil {
		return m.DokuInvoiceStatus
	}
	return DokuInvoiceStatus_NEW
}

func init() {
	proto.RegisterEnum("aggregates.kudaki_event.DokuInvoiceStatus", DokuInvoiceStatus_name, DokuInvoiceStatus_value)
	proto.RegisterType((*DokuInvoice)(nil), "aggregates.kudaki_event.DokuInvoice")
}

func init() {
	proto.RegisterFile("aggregates/kudaki_event/doku_invoice.proto", fileDescriptor_60136d5b6d0fd8b0)
}

var fileDescriptor_60136d5b6d0fd8b0 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdb, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0x4d, 0x7a, 0xdb, 0x9e, 0x6a, 0x2f, 0xe3, 0x65, 0x07, 0x41, 0x08, 0xbe, 0x18, 0x2a,
	0x9b, 0x80, 0xa2, 0xef, 0x6b, 0x5b, 0xa1, 0xb2, 0xfa, 0x90, 0xba, 0x08, 0xfb, 0x12, 0xa6, 0x99,
	0x43, 0x3b, 0x64, 0x93, 0x59, 0xe7, 0x52, 0xf1, 0x9f, 0xf1, 0x6f, 0x95, 0x4c, 0xd2, 0x1a, 0x5c,
	0xf6, 0x6d, 0xbe, 0xef, 0xfb, 0x25, 0xf9, 0x32, 0xe7, 0xc0, 0x9c, 0xed, 0x76, 0x0a, 0x77, 0xcc,
	0xa0, 0x8e, 0x73, 0xcb, 0x59, 0x2e, 0x52, 0x3c, 0x60, 0x69, 0x62, 0x2e, 0x73, 0x9b, 0x8a, 0xf2,
	0x20, 0x45, 0x86, 0xd1, 0x9d, 0x92, 0x46, 0x92, 0xf3, 0x7f, 0x6c, 0xd4, 0x66, 0x5f, 0xff, 0xe9,
	0xc2, 0x68, 0x29, 0x73, 0xbb, 0xae, 0x71, 0x32, 0x06, 0x5f, 0x70, 0xea, 0x05, 0x5e, 0xd8, 0x49,
	0x7c, 0xc1, 0x09, 0x81, 0xae, 0xb5, 0x82, 0x53, 0x3f, 0xf0, 0xc2, 0x61, 0xe2, 0xce, 0x64, 0x0e,
	0xb3, 0xf6, 0x3b, 0x52, 0x07, 0x74, 0x1c, 0x30, 0xa9, 0x83, 0x55, 0xe5, 0x5f, 0x57, 0xec, 0x0b,
	0xe8, 0xb3, 0x42, 0xda, 0xd2, 0xd0, 0x6e, 0xe0, 0x85, 0x7e, 0xd2, 0x28, 0xf2, 0x06, 0x26, 0x77,
	0x56, 0x65, 0x7b, 0xa6, 0x31, 0x6d, 0x80, 0x9e, 0x03, 0xc6, 0x47, 0xfb, 0xb2, 0x06, 0x3f, 0xc2,
	0xb9, 0x51, 0xac, 0xd4, 0x2c, 0x33, 0x42, 0x96, 0xa9, 0xe0, 0x69, 0x81, 0x15, 0x50, 0x1a, 0xda,
	0x77, 0x9f, 0x7c, 0xde, 0x8a, 0xd7, 0xfc, 0x6b, 0x13, 0x92, 0x67, 0xd0, 0xfb, 0x25, 0x15, 0xd7,
	0x74, 0xe0, 0xa8, 0x5a, 0x54, 0xd5, 0x15, 0xfe, 0xb4, 0xa8, 0x4d, 0xca, 0x99, 0xc1, 0xd4, 0x88,
	0x02, 0xe9, 0x99, 0xfb, 0xdb, 0x49, 0x13, 0x2c, 0x99, 0xc1, 0xef, 0xa2, 0x40, 0xf2, 0x12, 0xce,
	0x32, 0xab, 0x14, 0x96, 0xd9, 0x6f, 0x3a, 0x0c, 0xbc, 0xb0, 0x97, 0x9c, 0x34, 0x79, 0x0b, 0xb3,
	0x53, 0xfd, 0x13, 0x04, 0x0e, 0x9a, 0x1e, 0x83, 0xc5, 0x11, 0x7e, 0x05, 0xa0, 0x51, 0xeb, 0xba,
	0x3e, 0x1d, 0xb9, 0x3e, 0xc3, 0xc6, 0x59, 0xbb, 0x2b, 0x2e, 0x59, 0x81, 0xf4, 0x71, 0x7d, 0xc5,
	0xd5, 0xb9, 0x6a, 0x8f, 0x05, 0x13, 0xb7, 0xf4, 0x49, 0xdd, 0xde, 0x89, 0xea, 0x32, 0xb7, 0x4c,
	0xe7, 0x68, 0xe8, 0xd8, 0xd9, 0x8d, 0x22, 0x37, 0xf0, 0xb4, 0x3d, 0xf3, 0x54, 0x1b, 0x66, 0xac,
	0xa6, 0x93, 0xc0, 0x0b, 0xc7, 0xef, 0xe6, 0xd1, 0x03, 0xb3, 0x8f, 0x5a, 0x73, 0xdf, 0xb8, 0x27,
	0x92, 0x19, 0xff, 0xdf, 0x9a, 0x7f, 0x80, 0xd9, 0x3d, 0x8e, 0x0c, 0xa0, 0xf3, 0x6d, 0xf5, 0x63,
	0xfa, 0x88, 0x8c, 0x60, 0xb0, 0xb9, 0x5e, 0x2c, 0x56, 0x9b, 0xcd, 0xd4, 0x23, 0x00, 0xfd, 0xcf,
	0x97, 0xeb, 0xab, 0xd5, 0x72, 0xea, 0x7f, 0xba, 0xba, 0xf9, 0xb2, 0x13, 0x66, 0x6f, 0xb7, 0x51,
	0x26, 0x8b, 0x58, 0xdc, 0xee, 0x59, 0x51, 0xec, 0x39, 0x6f, 0x16, 0xf5, 0xc2, 0x15, 0xb8, 0xd0,
	0xa8, 0x0e, 0x22, 0xc3, 0x18, 0x4b, 0x23, 0x8c, 0x40, 0x1d, 0x3f, 0xb0, 0xd1, 0xdb, 0xbe, 0xdb,
	0xe2, 0xf7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xfd, 0xb8, 0x0c, 0xf3, 0x02, 0x00, 0x00,
}
