// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/kudaki_event.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	kudaki_event "github.com/ilhammhdd/kudaki-gateway-service/entities/aggregates/kudaki_event"
	user "github.com/ilhammhdd/kudaki-gateway-service/entities/aggregates/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventServiceCommandTopic int32

const (
	EventServiceCommandTopic_ADD_KUDAKI_EVENT            EventServiceCommandTopic = 0
	EventServiceCommandTopic_UPDATE_KUDAKI_EVENT         EventServiceCommandTopic = 1
	EventServiceCommandTopic_DELETE_KUDAKI_EVENT         EventServiceCommandTopic = 2
	EventServiceCommandTopic_RETRIEVE_KUDAKI_EVENT       EventServiceCommandTopic = 3
	EventServiceCommandTopic_RETRIEVE_KUDAKI_EVENTS      EventServiceCommandTopic = 4
	EventServiceCommandTopic_RETRIEVE_ORGANIZER_INVOICES EventServiceCommandTopic = 5
	EventServiceCommandTopic_PUBLISH_KUDAKI_EVENT        EventServiceCommandTopic = 6
)

var EventServiceCommandTopic_name = map[int32]string{
	0: "ADD_KUDAKI_EVENT",
	1: "UPDATE_KUDAKI_EVENT",
	2: "DELETE_KUDAKI_EVENT",
	3: "RETRIEVE_KUDAKI_EVENT",
	4: "RETRIEVE_KUDAKI_EVENTS",
	5: "RETRIEVE_ORGANIZER_INVOICES",
	6: "PUBLISH_KUDAKI_EVENT",
}

var EventServiceCommandTopic_value = map[string]int32{
	"ADD_KUDAKI_EVENT":            0,
	"UPDATE_KUDAKI_EVENT":         1,
	"DELETE_KUDAKI_EVENT":         2,
	"RETRIEVE_KUDAKI_EVENT":       3,
	"RETRIEVE_KUDAKI_EVENTS":      4,
	"RETRIEVE_ORGANIZER_INVOICES": 5,
	"PUBLISH_KUDAKI_EVENT":        6,
}

func (x EventServiceCommandTopic) String() string {
	return proto.EnumName(EventServiceCommandTopic_name, int32(x))
}

func (EventServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{0}
}

type EventServiceEventTopic int32

const (
	EventServiceEventTopic_KUDAKI_EVENT_ADDED           EventServiceEventTopic = 0
	EventServiceEventTopic_KUDAKI_EVENT_UPDATED         EventServiceEventTopic = 1
	EventServiceEventTopic_KUDAKI_EVENT_DELETED         EventServiceEventTopic = 2
	EventServiceEventTopic_KUDAKI_EVENT_RETRIEVED       EventServiceEventTopic = 3
	EventServiceEventTopic_KUDAKI_EVENTS_RETRIEVED      EventServiceEventTopic = 4
	EventServiceEventTopic_ORGANIZER_INVOICES_RETRIEVED EventServiceEventTopic = 5
	EventServiceEventTopic_KUDAKI_EVENT_PUBLISHED       EventServiceEventTopic = 6
)

var EventServiceEventTopic_name = map[int32]string{
	0: "KUDAKI_EVENT_ADDED",
	1: "KUDAKI_EVENT_UPDATED",
	2: "KUDAKI_EVENT_DELETED",
	3: "KUDAKI_EVENT_RETRIEVED",
	4: "KUDAKI_EVENTS_RETRIEVED",
	5: "ORGANIZER_INVOICES_RETRIEVED",
	6: "KUDAKI_EVENT_PUBLISHED",
}

var EventServiceEventTopic_value = map[string]int32{
	"KUDAKI_EVENT_ADDED":           0,
	"KUDAKI_EVENT_UPDATED":         1,
	"KUDAKI_EVENT_DELETED":         2,
	"KUDAKI_EVENT_RETRIEVED":       3,
	"KUDAKI_EVENTS_RETRIEVED":      4,
	"ORGANIZER_INVOICES_RETRIEVED": 5,
	"KUDAKI_EVENT_PUBLISHED":       6,
}

func (x EventServiceEventTopic) String() string {
	return proto.EnumName(EventServiceEventTopic_name, int32(x))
}

func (EventServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{1}
}

type EventPaymentServiceCommandTopic int32

const (
	EventPaymentServiceCommandTopic_PAYMENT_REQUEST_DOKU EventPaymentServiceCommandTopic = 0
)

var EventPaymentServiceCommandTopic_name = map[int32]string{
	0: "PAYMENT_REQUEST_DOKU",
}

var EventPaymentServiceCommandTopic_value = map[string]int32{
	"PAYMENT_REQUEST_DOKU": 0,
}

func (x EventPaymentServiceCommandTopic) String() string {
	return proto.EnumName(EventPaymentServiceCommandTopic_name, int32(x))
}

func (EventPaymentServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{2}
}

type EventPaymentServiceEventTopic int32

const (
	EventPaymentServiceEventTopic_EVENT_DOKU_INVOICE_ISSUED   EventPaymentServiceEventTopic = 0
	EventPaymentServiceEventTopic_EVENT_DOKU_PAYMENT_IDENTIFY EventPaymentServiceEventTopic = 1
	EventPaymentServiceEventTopic_EVENT_DOKU_PAYMENT_REDIRECT EventPaymentServiceEventTopic = 2
	EventPaymentServiceEventTopic_EVENT_DOKU_PAYMENT_NOTIFY   EventPaymentServiceEventTopic = 3
	EventPaymentServiceEventTopic_PAYMENT_REQUESTED_DOKU      EventPaymentServiceEventTopic = 4
)

var EventPaymentServiceEventTopic_name = map[int32]string{
	0: "EVENT_DOKU_INVOICE_ISSUED",
	1: "EVENT_DOKU_PAYMENT_IDENTIFY",
	2: "EVENT_DOKU_PAYMENT_REDIRECT",
	3: "EVENT_DOKU_PAYMENT_NOTIFY",
	4: "PAYMENT_REQUESTED_DOKU",
}

var EventPaymentServiceEventTopic_value = map[string]int32{
	"EVENT_DOKU_INVOICE_ISSUED":   0,
	"EVENT_DOKU_PAYMENT_IDENTIFY": 1,
	"EVENT_DOKU_PAYMENT_REDIRECT": 2,
	"EVENT_DOKU_PAYMENT_NOTIFY":   3,
	"PAYMENT_REQUESTED_DOKU":      4,
}

func (x EventPaymentServiceEventTopic) String() string {
	return proto.EnumName(EventPaymentServiceEventTopic_name, int32(x))
}

func (EventPaymentServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{3}
}

type AddKudakiEvent struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Venue                string   `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DurationFrom         int64    `protobuf:"varint,4,opt,name=duration_from,json=durationFrom,proto3" json:"duration_from,omitempty"`
	DurationTo           int64    `protobuf:"varint,5,opt,name=duration_to,json=durationTo,proto3" json:"duration_to,omitempty"`
	AdDurationFrom       int64    `protobuf:"varint,7,opt,name=ad_duration_from,json=adDurationFrom,proto3" json:"ad_duration_from,omitempty"`
	AdDurationTo         int64    `protobuf:"varint,8,opt,name=ad_duration_to,json=adDurationTo,proto3" json:"ad_duration_to,omitempty"`
	KudakiToken          string   `protobuf:"bytes,9,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	FilePath             string   `protobuf:"bytes,10,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddKudakiEvent) Reset()         { *m = AddKudakiEvent{} }
func (m *AddKudakiEvent) String() string { return proto.CompactTextString(m) }
func (*AddKudakiEvent) ProtoMessage()    {}
func (*AddKudakiEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{0}
}

func (m *AddKudakiEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddKudakiEvent.Unmarshal(m, b)
}
func (m *AddKudakiEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddKudakiEvent.Marshal(b, m, deterministic)
}
func (m *AddKudakiEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddKudakiEvent.Merge(m, src)
}
func (m *AddKudakiEvent) XXX_Size() int {
	return xxx_messageInfo_AddKudakiEvent.Size(m)
}
func (m *AddKudakiEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AddKudakiEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AddKudakiEvent proto.InternalMessageInfo

func (m *AddKudakiEvent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AddKudakiEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddKudakiEvent) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *AddKudakiEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddKudakiEvent) GetDurationFrom() int64 {
	if m != nil {
		return m.DurationFrom
	}
	return 0
}

func (m *AddKudakiEvent) GetDurationTo() int64 {
	if m != nil {
		return m.DurationTo
	}
	return 0
}

func (m *AddKudakiEvent) GetAdDurationFrom() int64 {
	if m != nil {
		return m.AdDurationFrom
	}
	return 0
}

func (m *AddKudakiEvent) GetAdDurationTo() int64 {
	if m != nil {
		return m.AdDurationTo
	}
	return 0
}

func (m *AddKudakiEvent) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *AddKudakiEvent) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type DeleteKudakiEvent struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventUuid            string   `protobuf:"bytes,2,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,3,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteKudakiEvent) Reset()         { *m = DeleteKudakiEvent{} }
func (m *DeleteKudakiEvent) String() string { return proto.CompactTextString(m) }
func (*DeleteKudakiEvent) ProtoMessage()    {}
func (*DeleteKudakiEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{1}
}

func (m *DeleteKudakiEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteKudakiEvent.Unmarshal(m, b)
}
func (m *DeleteKudakiEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteKudakiEvent.Marshal(b, m, deterministic)
}
func (m *DeleteKudakiEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteKudakiEvent.Merge(m, src)
}
func (m *DeleteKudakiEvent) XXX_Size() int {
	return xxx_messageInfo_DeleteKudakiEvent.Size(m)
}
func (m *DeleteKudakiEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteKudakiEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteKudakiEvent proto.InternalMessageInfo

func (m *DeleteKudakiEvent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DeleteKudakiEvent) GetEventUuid() string {
	if m != nil {
		return m.EventUuid
	}
	return ""
}

func (m *DeleteKudakiEvent) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

type RetrieveOrganizerInvoices struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	ResultSchema         []byte   `protobuf:"bytes,3,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveOrganizerInvoices) Reset()         { *m = RetrieveOrganizerInvoices{} }
func (m *RetrieveOrganizerInvoices) String() string { return proto.CompactTextString(m) }
func (*RetrieveOrganizerInvoices) ProtoMessage()    {}
func (*RetrieveOrganizerInvoices) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{2}
}

func (m *RetrieveOrganizerInvoices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveOrganizerInvoices.Unmarshal(m, b)
}
func (m *RetrieveOrganizerInvoices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveOrganizerInvoices.Marshal(b, m, deterministic)
}
func (m *RetrieveOrganizerInvoices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveOrganizerInvoices.Merge(m, src)
}
func (m *RetrieveOrganizerInvoices) XXX_Size() int {
	return xxx_messageInfo_RetrieveOrganizerInvoices.Size(m)
}
func (m *RetrieveOrganizerInvoices) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveOrganizerInvoices.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveOrganizerInvoices proto.InternalMessageInfo

func (m *RetrieveOrganizerInvoices) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveOrganizerInvoices) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveOrganizerInvoices) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type RetrieveKudakiEvent struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiEventUuid      string   `protobuf:"bytes,2,opt,name=kudaki_event_uuid,json=kudakiEventUuid,proto3" json:"kudaki_event_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveKudakiEvent) Reset()         { *m = RetrieveKudakiEvent{} }
func (m *RetrieveKudakiEvent) String() string { return proto.CompactTextString(m) }
func (*RetrieveKudakiEvent) ProtoMessage()    {}
func (*RetrieveKudakiEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{3}
}

func (m *RetrieveKudakiEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveKudakiEvent.Unmarshal(m, b)
}
func (m *RetrieveKudakiEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveKudakiEvent.Marshal(b, m, deterministic)
}
func (m *RetrieveKudakiEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveKudakiEvent.Merge(m, src)
}
func (m *RetrieveKudakiEvent) XXX_Size() int {
	return xxx_messageInfo_RetrieveKudakiEvent.Size(m)
}
func (m *RetrieveKudakiEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveKudakiEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveKudakiEvent proto.InternalMessageInfo

func (m *RetrieveKudakiEvent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveKudakiEvent) GetKudakiEventUuid() string {
	if m != nil {
		return m.KudakiEventUuid
	}
	return ""
}

type PublishKudakiEvent struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	KudakiEventUuid      string   `protobuf:"bytes,3,opt,name=kudaki_event_uuid,json=kudakiEventUuid,proto3" json:"kudaki_event_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishKudakiEvent) Reset()         { *m = PublishKudakiEvent{} }
func (m *PublishKudakiEvent) String() string { return proto.CompactTextString(m) }
func (*PublishKudakiEvent) ProtoMessage()    {}
func (*PublishKudakiEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{4}
}

func (m *PublishKudakiEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishKudakiEvent.Unmarshal(m, b)
}
func (m *PublishKudakiEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishKudakiEvent.Marshal(b, m, deterministic)
}
func (m *PublishKudakiEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishKudakiEvent.Merge(m, src)
}
func (m *PublishKudakiEvent) XXX_Size() int {
	return xxx_messageInfo_PublishKudakiEvent.Size(m)
}
func (m *PublishKudakiEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishKudakiEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PublishKudakiEvent proto.InternalMessageInfo

func (m *PublishKudakiEvent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PublishKudakiEvent) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *PublishKudakiEvent) GetKudakiEventUuid() string {
	if m != nil {
		return m.KudakiEventUuid
	}
	return ""
}

type KudakiEventAdded struct {
	Uid                  string                    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Organizer            *user.User                `protobuf:"bytes,2,opt,name=organizer,proto3" json:"organizer,omitempty"`
	EventStatus          *Status                   `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEvent          *kudaki_event.KudakiEvent `protobuf:"bytes,4,opt,name=kudaki_event,json=kudakiEvent,proto3" json:"kudaki_event,omitempty"`
	AddKudakiEvent       *AddKudakiEvent           `protobuf:"bytes,5,opt,name=add_kudaki_event,json=addKudakiEvent,proto3" json:"add_kudaki_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *KudakiEventAdded) Reset()         { *m = KudakiEventAdded{} }
func (m *KudakiEventAdded) String() string { return proto.CompactTextString(m) }
func (*KudakiEventAdded) ProtoMessage()    {}
func (*KudakiEventAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{5}
}

func (m *KudakiEventAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KudakiEventAdded.Unmarshal(m, b)
}
func (m *KudakiEventAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KudakiEventAdded.Marshal(b, m, deterministic)
}
func (m *KudakiEventAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KudakiEventAdded.Merge(m, src)
}
func (m *KudakiEventAdded) XXX_Size() int {
	return xxx_messageInfo_KudakiEventAdded.Size(m)
}
func (m *KudakiEventAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_KudakiEventAdded.DiscardUnknown(m)
}

var xxx_messageInfo_KudakiEventAdded proto.InternalMessageInfo

func (m *KudakiEventAdded) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *KudakiEventAdded) GetOrganizer() *user.User {
	if m != nil {
		return m.Organizer
	}
	return nil
}

func (m *KudakiEventAdded) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *KudakiEventAdded) GetKudakiEvent() *kudaki_event.KudakiEvent {
	if m != nil {
		return m.KudakiEvent
	}
	return nil
}

func (m *KudakiEventAdded) GetAddKudakiEvent() *AddKudakiEvent {
	if m != nil {
		return m.AddKudakiEvent
	}
	return nil
}

type KudakiEventDeleted struct {
	Uid                  string                    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Organizer            *user.User                `protobuf:"bytes,2,opt,name=organizer,proto3" json:"organizer,omitempty"`
	EventStatus          *Status                   `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEvent          *kudaki_event.KudakiEvent `protobuf:"bytes,4,opt,name=kudaki_event,json=kudakiEvent,proto3" json:"kudaki_event,omitempty"`
	DeleteKudakiEvent    *DeleteKudakiEvent        `protobuf:"bytes,5,opt,name=delete_kudaki_event,json=deleteKudakiEvent,proto3" json:"delete_kudaki_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *KudakiEventDeleted) Reset()         { *m = KudakiEventDeleted{} }
func (m *KudakiEventDeleted) String() string { return proto.CompactTextString(m) }
func (*KudakiEventDeleted) ProtoMessage()    {}
func (*KudakiEventDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{6}
}

func (m *KudakiEventDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KudakiEventDeleted.Unmarshal(m, b)
}
func (m *KudakiEventDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KudakiEventDeleted.Marshal(b, m, deterministic)
}
func (m *KudakiEventDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KudakiEventDeleted.Merge(m, src)
}
func (m *KudakiEventDeleted) XXX_Size() int {
	return xxx_messageInfo_KudakiEventDeleted.Size(m)
}
func (m *KudakiEventDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_KudakiEventDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_KudakiEventDeleted proto.InternalMessageInfo

func (m *KudakiEventDeleted) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *KudakiEventDeleted) GetOrganizer() *user.User {
	if m != nil {
		return m.Organizer
	}
	return nil
}

func (m *KudakiEventDeleted) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *KudakiEventDeleted) GetKudakiEvent() *kudaki_event.KudakiEvent {
	if m != nil {
		return m.KudakiEvent
	}
	return nil
}

func (m *KudakiEventDeleted) GetDeleteKudakiEvent() *DeleteKudakiEvent {
	if m != nil {
		return m.DeleteKudakiEvent
	}
	return nil
}

type OrganizerInvoicesRetrieved struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Organizer            *user.User `protobuf:"bytes,2,opt,name=organizer,proto3" json:"organizer,omitempty"`
	EventStatus          *Status    `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Result               []byte     `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrganizerInvoicesRetrieved) Reset()         { *m = OrganizerInvoicesRetrieved{} }
func (m *OrganizerInvoicesRetrieved) String() string { return proto.CompactTextString(m) }
func (*OrganizerInvoicesRetrieved) ProtoMessage()    {}
func (*OrganizerInvoicesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{7}
}

func (m *OrganizerInvoicesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizerInvoicesRetrieved.Unmarshal(m, b)
}
func (m *OrganizerInvoicesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizerInvoicesRetrieved.Marshal(b, m, deterministic)
}
func (m *OrganizerInvoicesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizerInvoicesRetrieved.Merge(m, src)
}
func (m *OrganizerInvoicesRetrieved) XXX_Size() int {
	return xxx_messageInfo_OrganizerInvoicesRetrieved.Size(m)
}
func (m *OrganizerInvoicesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizerInvoicesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizerInvoicesRetrieved proto.InternalMessageInfo

func (m *OrganizerInvoicesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrganizerInvoicesRetrieved) GetOrganizer() *user.User {
	if m != nil {
		return m.Organizer
	}
	return nil
}

func (m *OrganizerInvoicesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrganizerInvoicesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type KudakiEventRetrieved struct {
	Uid                  string                    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus          *Status                   `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEvent          *kudaki_event.KudakiEvent `protobuf:"bytes,3,opt,name=kudaki_event,json=kudakiEvent,proto3" json:"kudaki_event,omitempty"`
	PaymentStatus        string                    `protobuf:"bytes,4,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *KudakiEventRetrieved) Reset()         { *m = KudakiEventRetrieved{} }
func (m *KudakiEventRetrieved) String() string { return proto.CompactTextString(m) }
func (*KudakiEventRetrieved) ProtoMessage()    {}
func (*KudakiEventRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{8}
}

func (m *KudakiEventRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KudakiEventRetrieved.Unmarshal(m, b)
}
func (m *KudakiEventRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KudakiEventRetrieved.Marshal(b, m, deterministic)
}
func (m *KudakiEventRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KudakiEventRetrieved.Merge(m, src)
}
func (m *KudakiEventRetrieved) XXX_Size() int {
	return xxx_messageInfo_KudakiEventRetrieved.Size(m)
}
func (m *KudakiEventRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_KudakiEventRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_KudakiEventRetrieved proto.InternalMessageInfo

func (m *KudakiEventRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *KudakiEventRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *KudakiEventRetrieved) GetKudakiEvent() *kudaki_event.KudakiEvent {
	if m != nil {
		return m.KudakiEvent
	}
	return nil
}

func (m *KudakiEventRetrieved) GetPaymentStatus() string {
	if m != nil {
		return m.PaymentStatus
	}
	return ""
}

type KudakiEventPublished struct {
	Uid                  string                    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Publisher            *user.User                `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`
	EventStatus          *Status                   `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	KudakiEvent          *kudaki_event.KudakiEvent `protobuf:"bytes,4,opt,name=kudaki_event,json=kudakiEvent,proto3" json:"kudaki_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *KudakiEventPublished) Reset()         { *m = KudakiEventPublished{} }
func (m *KudakiEventPublished) String() string { return proto.CompactTextString(m) }
func (*KudakiEventPublished) ProtoMessage()    {}
func (*KudakiEventPublished) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{9}
}

func (m *KudakiEventPublished) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KudakiEventPublished.Unmarshal(m, b)
}
func (m *KudakiEventPublished) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KudakiEventPublished.Marshal(b, m, deterministic)
}
func (m *KudakiEventPublished) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KudakiEventPublished.Merge(m, src)
}
func (m *KudakiEventPublished) XXX_Size() int {
	return xxx_messageInfo_KudakiEventPublished.Size(m)
}
func (m *KudakiEventPublished) XXX_DiscardUnknown() {
	xxx_messageInfo_KudakiEventPublished.DiscardUnknown(m)
}

var xxx_messageInfo_KudakiEventPublished proto.InternalMessageInfo

func (m *KudakiEventPublished) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *KudakiEventPublished) GetPublisher() *user.User {
	if m != nil {
		return m.Publisher
	}
	return nil
}

func (m *KudakiEventPublished) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *KudakiEventPublished) GetKudakiEvent() *kudaki_event.KudakiEvent {
	if m != nil {
		return m.KudakiEvent
	}
	return nil
}

type PaymentRequestDoku struct {
	Uid                   string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken           string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	TransactionIdMerchant string   `protobuf:"bytes,3,opt,name=transaction_id_merchant,json=transactionIdMerchant,proto3" json:"transaction_id_merchant,omitempty"`
	SessionId             string   `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HashedWords           string   `protobuf:"bytes,5,opt,name=hashed_words,json=hashedWords,proto3" json:"hashed_words,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *PaymentRequestDoku) Reset()         { *m = PaymentRequestDoku{} }
func (m *PaymentRequestDoku) String() string { return proto.CompactTextString(m) }
func (*PaymentRequestDoku) ProtoMessage()    {}
func (*PaymentRequestDoku) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{10}
}

func (m *PaymentRequestDoku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequestDoku.Unmarshal(m, b)
}
func (m *PaymentRequestDoku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequestDoku.Marshal(b, m, deterministic)
}
func (m *PaymentRequestDoku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequestDoku.Merge(m, src)
}
func (m *PaymentRequestDoku) XXX_Size() int {
	return xxx_messageInfo_PaymentRequestDoku.Size(m)
}
func (m *PaymentRequestDoku) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequestDoku.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequestDoku proto.InternalMessageInfo

func (m *PaymentRequestDoku) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PaymentRequestDoku) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *PaymentRequestDoku) GetTransactionIdMerchant() string {
	if m != nil {
		return m.TransactionIdMerchant
	}
	return ""
}

func (m *PaymentRequestDoku) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *PaymentRequestDoku) GetHashedWords() string {
	if m != nil {
		return m.HashedWords
	}
	return ""
}

type KudakiEventDokuInvoiceIssued struct {
	Uid                  string                    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Organizer            *user.User                `protobuf:"bytes,2,opt,name=organizer,proto3" json:"organizer,omitempty"`
	EventStatus          *Status                   `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	DokuInvoice          *kudaki_event.DokuInvoice `protobuf:"bytes,4,opt,name=doku_invoice,json=dokuInvoice,proto3" json:"doku_invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *KudakiEventDokuInvoiceIssued) Reset()         { *m = KudakiEventDokuInvoiceIssued{} }
func (m *KudakiEventDokuInvoiceIssued) String() string { return proto.CompactTextString(m) }
func (*KudakiEventDokuInvoiceIssued) ProtoMessage()    {}
func (*KudakiEventDokuInvoiceIssued) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{11}
}

func (m *KudakiEventDokuInvoiceIssued) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KudakiEventDokuInvoiceIssued.Unmarshal(m, b)
}
func (m *KudakiEventDokuInvoiceIssued) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KudakiEventDokuInvoiceIssued.Marshal(b, m, deterministic)
}
func (m *KudakiEventDokuInvoiceIssued) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KudakiEventDokuInvoiceIssued.Merge(m, src)
}
func (m *KudakiEventDokuInvoiceIssued) XXX_Size() int {
	return xxx_messageInfo_KudakiEventDokuInvoiceIssued.Size(m)
}
func (m *KudakiEventDokuInvoiceIssued) XXX_DiscardUnknown() {
	xxx_messageInfo_KudakiEventDokuInvoiceIssued.DiscardUnknown(m)
}

var xxx_messageInfo_KudakiEventDokuInvoiceIssued proto.InternalMessageInfo

func (m *KudakiEventDokuInvoiceIssued) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *KudakiEventDokuInvoiceIssued) GetOrganizer() *user.User {
	if m != nil {
		return m.Organizer
	}
	return nil
}

func (m *KudakiEventDokuInvoiceIssued) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *KudakiEventDokuInvoiceIssued) GetDokuInvoice() *kudaki_event.DokuInvoice {
	if m != nil {
		return m.DokuInvoice
	}
	return nil
}

type PaymentRequestedDoku struct {
	Uid                  string                    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Organizer            *user.User                `protobuf:"bytes,2,opt,name=organizer,proto3" json:"organizer,omitempty"`
	EventStatus          *Status                   `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	DokuInvoice          *kudaki_event.DokuInvoice `protobuf:"bytes,4,opt,name=doku_invoice,json=dokuInvoice,proto3" json:"doku_invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PaymentRequestedDoku) Reset()         { *m = PaymentRequestedDoku{} }
func (m *PaymentRequestedDoku) String() string { return proto.CompactTextString(m) }
func (*PaymentRequestedDoku) ProtoMessage()    {}
func (*PaymentRequestedDoku) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa36ed941739bd5b, []int{12}
}

func (m *PaymentRequestedDoku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequestedDoku.Unmarshal(m, b)
}
func (m *PaymentRequestedDoku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequestedDoku.Marshal(b, m, deterministic)
}
func (m *PaymentRequestedDoku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequestedDoku.Merge(m, src)
}
func (m *PaymentRequestedDoku) XXX_Size() int {
	return xxx_messageInfo_PaymentRequestedDoku.Size(m)
}
func (m *PaymentRequestedDoku) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequestedDoku.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequestedDoku proto.InternalMessageInfo

func (m *PaymentRequestedDoku) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PaymentRequestedDoku) GetOrganizer() *user.User {
	if m != nil {
		return m.Organizer
	}
	return nil
}

func (m *PaymentRequestedDoku) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *PaymentRequestedDoku) GetDokuInvoice() *kudaki_event.DokuInvoice {
	if m != nil {
		return m.DokuInvoice
	}
	return nil
}

func init() {
	proto.RegisterEnum("aggregates.event.EventServiceCommandTopic", EventServiceCommandTopic_name, EventServiceCommandTopic_value)
	proto.RegisterEnum("aggregates.event.EventServiceEventTopic", EventServiceEventTopic_name, EventServiceEventTopic_value)
	proto.RegisterEnum("aggregates.event.EventPaymentServiceCommandTopic", EventPaymentServiceCommandTopic_name, EventPaymentServiceCommandTopic_value)
	proto.RegisterEnum("aggregates.event.EventPaymentServiceEventTopic", EventPaymentServiceEventTopic_name, EventPaymentServiceEventTopic_value)
	proto.RegisterType((*AddKudakiEvent)(nil), "aggregates.event.AddKudakiEvent")
	proto.RegisterType((*DeleteKudakiEvent)(nil), "aggregates.event.DeleteKudakiEvent")
	proto.RegisterType((*RetrieveOrganizerInvoices)(nil), "aggregates.event.RetrieveOrganizerInvoices")
	proto.RegisterType((*RetrieveKudakiEvent)(nil), "aggregates.event.RetrieveKudakiEvent")
	proto.RegisterType((*PublishKudakiEvent)(nil), "aggregates.event.PublishKudakiEvent")
	proto.RegisterType((*KudakiEventAdded)(nil), "aggregates.event.KudakiEventAdded")
	proto.RegisterType((*KudakiEventDeleted)(nil), "aggregates.event.KudakiEventDeleted")
	proto.RegisterType((*OrganizerInvoicesRetrieved)(nil), "aggregates.event.OrganizerInvoicesRetrieved")
	proto.RegisterType((*KudakiEventRetrieved)(nil), "aggregates.event.KudakiEventRetrieved")
	proto.RegisterType((*KudakiEventPublished)(nil), "aggregates.event.KudakiEventPublished")
	proto.RegisterType((*PaymentRequestDoku)(nil), "aggregates.event.PaymentRequestDoku")
	proto.RegisterType((*KudakiEventDokuInvoiceIssued)(nil), "aggregates.event.KudakiEventDokuInvoiceIssued")
	proto.RegisterType((*PaymentRequestedDoku)(nil), "aggregates.event.PaymentRequestedDoku")
}

func init() { proto.RegisterFile("events/kudaki_event.proto", fileDescriptor_fa36ed941739bd5b) }

var fileDescriptor_fa36ed941739bd5b = []byte{
	// 1089 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x4f, 0x4f, 0xe3, 0x46,
	0x14, 0xc7, 0x49, 0xa0, 0x9b, 0x97, 0x40, 0xcd, 0xf0, 0xcf, 0x84, 0x45, 0x50, 0xb3, 0x95, 0x50,
	0xa4, 0x0d, 0x15, 0x2b, 0xf5, 0xb2, 0xea, 0x21, 0x8b, 0xbd, 0x5b, 0x97, 0x5d, 0x42, 0xed, 0x84,
	0x6a, 0xf7, 0x62, 0x0d, 0x99, 0xd9, 0xc4, 0x0a, 0x8e, 0x53, 0x8f, 0xcd, 0x6a, 0xfb, 0x69, 0x7a,
	0xaf, 0xfa, 0x09, 0x7a, 0x6c, 0x4f, 0x3d, 0xf7, 0x50, 0xa9, 0x97, 0x7e, 0x94, 0x6a, 0x66, 0x1c,
	0x18, 0x27, 0x01, 0xda, 0xbd, 0xa0, 0xee, 0x05, 0x79, 0x7e, 0xbf, 0xe7, 0xf7, 0xde, 0xef, 0xfd,
	0x99, 0x60, 0xd8, 0xa4, 0x97, 0x74, 0x98, 0xb0, 0x83, 0x41, 0x4a, 0xf0, 0x20, 0xf0, 0xc5, 0xa9,
	0x31, 0x8a, 0xa3, 0x24, 0x42, 0x3a, 0xee, 0xf5, 0x62, 0xda, 0xc3, 0x09, 0x65, 0x0d, 0x81, 0xd7,
	0x6a, 0xd7, 0xc8, 0x41, 0xca, 0x68, 0x2c, 0xfe, 0x48, 0xeb, 0x5a, 0x5d, 0xe1, 0x54, 0x67, 0x07,
	0x24, 0x1a, 0xa4, 0x7e, 0x30, 0xbc, 0x8c, 0x82, 0x2e, 0xbd, 0xcb, 0x76, 0x3a, 0x8b, 0xda, 0x4a,
	0x96, 0x20, 0x4b, 0x70, 0x92, 0x32, 0x09, 0x9a, 0xbf, 0x15, 0x60, 0xa9, 0x49, 0xc8, 0xb1, 0x30,
	0xb7, 0xb9, 0x01, 0xd2, 0xa1, 0x98, 0x06, 0xc4, 0xd0, 0x76, 0xb5, 0xfd, 0xb2, 0xcb, 0x1f, 0x11,
	0x82, 0xd2, 0x10, 0x87, 0xd4, 0x58, 0x10, 0x90, 0x78, 0x46, 0xab, 0x30, 0x7f, 0x49, 0x87, 0x29,
	0x35, 0x0a, 0x02, 0x94, 0x07, 0xb4, 0x0b, 0x15, 0x42, 0x59, 0x37, 0x0e, 0x46, 0x49, 0x10, 0x0d,
	0x8d, 0xa2, 0xe0, 0x54, 0x08, 0xed, 0xc1, 0x22, 0x49, 0x63, 0xcc, 0x9f, 0xfd, 0xb7, 0x71, 0x14,
	0x1a, 0xa5, 0x5d, 0x6d, 0xbf, 0xe8, 0x56, 0xc7, 0xe0, 0xf3, 0x38, 0x0a, 0xd1, 0x0e, 0x54, 0xae,
	0x8c, 0x92, 0xc8, 0x98, 0x17, 0x26, 0x30, 0x86, 0xda, 0x11, 0xda, 0x07, 0x1d, 0x13, 0x3f, 0xef,
	0xe8, 0x13, 0x61, 0xb5, 0x84, 0x89, 0xa5, 0xba, 0x7a, 0x04, 0x4b, 0xaa, 0x65, 0x12, 0x19, 0x0f,
	0x64, 0xc0, 0x6b, 0xbb, 0x76, 0x84, 0x3e, 0x83, 0x6a, 0x56, 0xb1, 0x24, 0x1a, 0xd0, 0xa1, 0x51,
	0x96, 0x89, 0x4b, 0xac, 0xcd, 0x21, 0xb4, 0x05, 0xe5, 0xb7, 0xc1, 0x05, 0xf5, 0x47, 0x38, 0xe9,
	0x1b, 0x20, 0xf8, 0x07, 0x1c, 0x38, 0xc5, 0x49, 0xdf, 0xec, 0xc1, 0xb2, 0x45, 0x2f, 0x68, 0x42,
	0x6f, 0x2f, 0xe4, 0x36, 0x80, 0x68, 0x82, 0x9f, 0x72, 0x42, 0x56, 0xae, 0x2c, 0x90, 0x0e, 0xa7,
	0x27, 0xb3, 0x28, 0x4e, 0x65, 0x61, 0xa6, 0xb0, 0xe9, 0xd2, 0x24, 0x0e, 0xe8, 0x25, 0x6d, 0xc5,
	0x3d, 0x3c, 0x0c, 0x7e, 0xa0, 0xb1, 0x23, 0x47, 0x82, 0xcd, 0x08, 0x38, 0xe9, 0xb1, 0x30, 0xad,
	0x6b, 0x0f, 0x16, 0x63, 0xca, 0xd2, 0x8b, 0xc4, 0x67, 0xdd, 0x3e, 0x0d, 0xb1, 0x88, 0x5a, 0x75,
	0xab, 0x12, 0xf4, 0x04, 0x66, 0x7a, 0xb0, 0x32, 0x0e, 0x7b, 0xbb, 0xc2, 0x3a, 0x2c, 0xab, 0xa3,
	0xa7, 0x0a, 0xfd, 0x74, 0x70, 0xfd, 0x26, 0x97, 0x6b, 0xa6, 0x80, 0x4e, 0xd3, 0xf3, 0x8b, 0x80,
	0xf5, 0x6f, 0xf7, 0xf9, 0x2f, 0x44, 0xcc, 0x0c, 0x5b, 0x9c, 0x1d, 0xf6, 0xc7, 0x02, 0xe8, 0x4a,
	0xc0, 0x26, 0x21, 0x94, 0xcc, 0x88, 0xfa, 0x04, 0xca, 0xd1, 0xb8, 0xc2, 0x22, 0x64, 0xe5, 0x70,
	0xad, 0xa1, 0x2c, 0xb2, 0xd8, 0xd8, 0x0e, 0xa3, 0xb1, 0x7b, 0x6d, 0x87, 0xbe, 0x80, 0xaa, 0x4c,
	0x40, 0x2e, 0x99, 0x48, 0xa1, 0x72, 0xb8, 0x28, 0xb7, 0xbe, 0xe1, 0x09, 0xd0, 0xad, 0x88, 0x93,
	0x3c, 0xa0, 0x17, 0x57, 0xe2, 0x04, 0x2a, 0xd6, 0xa1, 0x72, 0xf8, 0x48, 0x8d, 0x94, 0xdb, 0x65,
	0x25, 0xf3, 0x71, 0x09, 0x64, 0xdd, 0xbe, 0xe1, 0x2b, 0x41, 0xfc, 0x9c, 0xb3, 0x79, 0xe1, 0x6c,
	0xb7, 0x31, 0x79, 0xff, 0x34, 0xf2, 0x2b, 0xcf, 0x97, 0x46, 0x3d, 0x9b, 0x3f, 0x15, 0x00, 0x29,
	0x67, 0x39, 0xda, 0x1f, 0x43, 0x91, 0x3c, 0x58, 0x21, 0x42, 0xcc, 0xac, 0x3a, 0xed, 0x4d, 0xd7,
	0x69, 0x6a, 0xa9, 0xdd, 0x65, 0x32, 0x09, 0x99, 0x3f, 0x6b, 0x50, 0x9b, 0x5a, 0xc6, 0xf1, 0xba,
	0xdc, 0x63, 0xd5, 0xd6, 0x61, 0x41, 0x2e, 0xb1, 0xa8, 0x57, 0xd5, 0xcd, 0x4e, 0xe6, 0xef, 0x1a,
	0xac, 0xaa, 0x92, 0x6e, 0xc9, 0x74, 0x32, 0x68, 0xe1, 0x3f, 0xb7, 0xaa, 0xf8, 0xa1, 0xad, 0xfa,
	0x1c, 0x96, 0x46, 0xf8, 0x7d, 0xa8, 0x04, 0x2f, 0x89, 0xbc, 0x16, 0x33, 0x54, 0xc6, 0x33, 0xff,
	0xcc, 0x8b, 0xc9, 0x2e, 0x94, 0x9b, 0xca, 0x3e, 0xca, 0xe8, 0xbb, 0xca, 0x7e, 0x65, 0x77, 0x8f,
	0xc3, 0x6a, 0xfe, 0xaa, 0x01, 0x3a, 0x95, 0x62, 0x5d, 0xfa, 0x7d, 0x4a, 0x59, 0x62, 0x45, 0x83,
	0xf4, 0xc3, 0x2e, 0xc8, 0x2f, 0x61, 0x23, 0x89, 0xf1, 0x90, 0xe1, 0xae, 0xf8, 0x19, 0x0c, 0x88,
	0x1f, 0xd2, 0xb8, 0xdb, 0xc7, 0x59, 0x87, 0xca, 0xee, 0x9a, 0x42, 0x3b, 0xe4, 0x55, 0x46, 0xf2,
	0x5f, 0x2c, 0x46, 0x19, 0x93, 0xef, 0x64, 0x1d, 0x28, 0x67, 0x88, 0x23, 0x22, 0xf7, 0x31, 0x2f,
	0xb7, 0xff, 0x2e, 0x8a, 0x09, 0x13, 0x8b, 0x54, 0x76, 0x2b, 0x12, 0xfb, 0x8e, 0x43, 0xe6, 0xdf,
	0x1a, 0x3c, 0x54, 0xef, 0x92, 0x68, 0x90, 0x66, 0x3b, 0xe2, 0x30, 0x96, 0xde, 0xf3, 0xad, 0xa2,
	0xfe, 0x4b, 0x75, 0x67, 0xa3, 0x94, 0xd4, 0xdd, 0x0a, 0xb9, 0x3e, 0x88, 0x19, 0xcc, 0x37, 0x8a,
	0x92, 0x1b, 0x5a, 0xf5, 0x3f, 0x93, 0x56, 0xff, 0x43, 0x03, 0x43, 0xf4, 0xcd, 0xa3, 0xf1, 0x65,
	0xd0, 0xa5, 0x47, 0x51, 0x18, 0xe2, 0x21, 0x69, 0x47, 0xa3, 0xa0, 0x8b, 0x56, 0x41, 0x6f, 0x5a,
	0x96, 0x7f, 0xdc, 0xb1, 0x9a, 0xc7, 0x8e, 0x6f, 0x9f, 0xd9, 0x27, 0x6d, 0x7d, 0x0e, 0x6d, 0xc0,
	0x4a, 0xe7, 0xd4, 0x6a, 0xb6, 0xed, 0x3c, 0xa1, 0x71, 0xc2, 0xb2, 0x5f, 0xda, 0x93, 0x44, 0x01,
	0x6d, 0xc2, 0x9a, 0x6b, 0xb7, 0x5d, 0xc7, 0x3e, 0x9b, 0xa0, 0x8a, 0xa8, 0x06, 0xeb, 0x33, 0x29,
	0x4f, 0x2f, 0xa1, 0x1d, 0xd8, 0xba, 0xe2, 0x5a, 0xee, 0x8b, 0xe6, 0x89, 0xf3, 0xc6, 0x76, 0x7d,
	0xe7, 0xe4, 0xac, 0xe5, 0x1c, 0xd9, 0x9e, 0x3e, 0x8f, 0x0c, 0x58, 0x3d, 0xed, 0x3c, 0x7b, 0xe9,
	0x78, 0x5f, 0xe7, 0xdd, 0x2e, 0xd4, 0xff, 0xd2, 0x60, 0x5d, 0x95, 0x25, 0x9e, 0xa5, 0xa8, 0x75,
	0x40, 0xaa, 0xb1, 0xdf, 0xb4, 0x2c, 0xdb, 0xd2, 0xe7, 0xb8, 0xb3, 0x1c, 0x2e, 0x35, 0x5a, 0xba,
	0x36, 0xc5, 0x48, 0x91, 0x96, 0x5e, 0xe0, 0xd9, 0xe7, 0x98, 0x71, 0xba, 0x96, 0x5e, 0x44, 0x5b,
	0xb0, 0x91, 0x13, 0xa4, 0x90, 0x25, 0xb4, 0x0b, 0x0f, 0xa7, 0x15, 0x29, 0x16, 0xf3, 0x53, 0xae,
	0x33, 0xa1, 0xb6, 0xa5, 0x2f, 0xd4, 0x9f, 0xc2, 0x8e, 0xbc, 0x0c, 0xb3, 0x9b, 0x72, 0x46, 0xeb,
	0x78, 0x69, 0x9a, 0xaf, 0x5f, 0xc9, 0xa4, 0xbe, 0xed, 0xd8, 0x5e, 0xdb, 0xb7, 0x5a, 0xc7, 0x1d,
	0x7d, 0xae, 0xfe, 0x8b, 0x06, 0xdb, 0x33, 0xde, 0x56, 0x2a, 0xb4, 0x0d, 0x9b, 0x99, 0xd0, 0xd6,
	0x71, 0x67, 0x9c, 0x9d, 0xef, 0x78, 0x5e, 0x47, 0x14, 0x6a, 0x07, 0xb6, 0x14, 0x7a, 0x1c, 0xc5,
	0xb1, 0xec, 0x93, 0xb6, 0xf3, 0xfc, 0xb5, 0xae, 0xdd, 0x60, 0xe0, 0xda, 0x96, 0xe3, 0xda, 0x47,
	0x7c, 0x1e, 0xf2, 0x01, 0xc6, 0x06, 0x27, 0x2d, 0xf1, 0xbe, 0x98, 0x89, 0x89, 0xdc, 0x6d, 0x4b,
	0x66, 0x5f, 0x7a, 0xf6, 0xd5, 0x9b, 0xa7, 0xbd, 0x20, 0xe9, 0xa7, 0xe7, 0x8d, 0x6e, 0x14, 0x1e,
	0x04, 0x17, 0x7d, 0x1c, 0x86, 0x7d, 0x42, 0xb2, 0xef, 0xa1, 0xc7, 0x7c, 0xf4, 0xdf, 0xe1, 0xf7,
	0x8f, 0x99, 0x14, 0xc5, 0x3f, 0xbb, 0xba, 0x98, 0x51, 0x76, 0x20, 0xbf, 0x8d, 0xce, 0x17, 0xc4,
	0x57, 0xd1, 0x93, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x59, 0x90, 0x93, 0x11, 0xcd, 0x0d, 0x00,
	0x00,
}
