settings:
  recovery:
    index: true
    events: false
    tools: false
  legacy:
    force: false
    interval: 0s
schema:
- name: kudaki-file-service
  path: .
  commands:
    clean:
      status: true
    run:
      status: true
  args:
    - -- KAFKA_BROKERS 178.62.107.160:29092
    - -- DB_PATH tcp(178.62.107.160:3306)
    - -- DB_USERNAME kudaki_file_repo
    - -- DB_PASSWORD kudakifilereporocks
    - -- DB_NAME kudaki_file
    - -- QUERY_DB_PATH tcp(178.62.107.160:3307)
    - -- QUERY_DB_USERNAME root
    - -- QUERY_DB_PASSWORD mysqlreplicarocks
    - -- QUERY_DB_NAME kudaki_file
    - -- KAFKA_VERSION 2.1.1
    - -- REST_PORT 9003
    - -- GATEWAY_SERVICE_REST_ADDRESS http://localhost:9001
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - .vendor-new
    scripts:
    - type: before
      command: taskkill /IM "kudaki-file-service.exe" /F
