// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/order.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	order "github.com/ilhammhdd/kudaki-user-auth-service/entities/aggregates/order"
	user "github.com/ilhammhdd/kudaki-user-auth-service/entities/aggregates/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//order service commands
type OrderServiceCommandTopic int32

const (
	OrderServiceCommandTopic_RETRIEVE_OWNERS_ORDER_HISTORIES  OrderServiceCommandTopic = 0
	OrderServiceCommandTopic_RETRIEVE_TENANTS_ORDER_HISTORIES OrderServiceCommandTopic = 1
	OrderServiceCommandTopic_OWNER_REVIEW_TENANT              OrderServiceCommandTopic = 2
	OrderServiceCommandTopic_TENANT_REVIEW_OWNER              OrderServiceCommandTopic = 3
	OrderServiceCommandTopic_TENANT_REVIEW_ITEMS              OrderServiceCommandTopic = 4
	OrderServiceCommandTopic_APPROVE_ORDER                    OrderServiceCommandTopic = 5
	OrderServiceCommandTopic_DISAPPROVE_ORDER                 OrderServiceCommandTopic = 6
)

var OrderServiceCommandTopic_name = map[int32]string{
	0: "RETRIEVE_OWNERS_ORDER_HISTORIES",
	1: "RETRIEVE_TENANTS_ORDER_HISTORIES",
	2: "OWNER_REVIEW_TENANT",
	3: "TENANT_REVIEW_OWNER",
	4: "TENANT_REVIEW_ITEMS",
	5: "APPROVE_ORDER",
	6: "DISAPPROVE_ORDER",
}

var OrderServiceCommandTopic_value = map[string]int32{
	"RETRIEVE_OWNERS_ORDER_HISTORIES":  0,
	"RETRIEVE_TENANTS_ORDER_HISTORIES": 1,
	"OWNER_REVIEW_TENANT":              2,
	"TENANT_REVIEW_OWNER":              3,
	"TENANT_REVIEW_ITEMS":              4,
	"APPROVE_ORDER":                    5,
	"DISAPPROVE_ORDER":                 6,
}

func (x OrderServiceCommandTopic) String() string {
	return proto.EnumName(OrderServiceCommandTopic_name, int32(x))
}

func (OrderServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{0}
}

//
//order service events
type OrderServiceEventTopic int32

const (
	OrderServiceEventTopic_OWNERS_ORDER_HISTORIES_RETRIEVED  OrderServiceEventTopic = 0
	OrderServiceEventTopic_TENANTS_ORDER_HISTORIES_RETRIEVED OrderServiceEventTopic = 1
	OrderServiceEventTopic_OWNER_REVIEWED_TENANT             OrderServiceEventTopic = 2
	OrderServiceEventTopic_TENANT_REVIEWED_OWNER             OrderServiceEventTopic = 3
	OrderServiceEventTopic_TENANT_REVIEWED_ITEMS             OrderServiceEventTopic = 4
	OrderServiceEventTopic_ORDER_APPROVED                    OrderServiceEventTopic = 5
	OrderServiceEventTopic_ORDER_DISAPPROVED                 OrderServiceEventTopic = 6
)

var OrderServiceEventTopic_name = map[int32]string{
	0: "OWNERS_ORDER_HISTORIES_RETRIEVED",
	1: "TENANTS_ORDER_HISTORIES_RETRIEVED",
	2: "OWNER_REVIEWED_TENANT",
	3: "TENANT_REVIEWED_OWNER",
	4: "TENANT_REVIEWED_ITEMS",
	5: "ORDER_APPROVED",
	6: "ORDER_DISAPPROVED",
}

var OrderServiceEventTopic_value = map[string]int32{
	"OWNERS_ORDER_HISTORIES_RETRIEVED":  0,
	"TENANTS_ORDER_HISTORIES_RETRIEVED": 1,
	"OWNER_REVIEWED_TENANT":             2,
	"TENANT_REVIEWED_OWNER":             3,
	"TENANT_REVIEWED_ITEMS":             4,
	"ORDER_APPROVED":                    5,
	"ORDER_DISAPPROVED":                 6,
}

func (x OrderServiceEventTopic) String() string {
	return proto.EnumName(OrderServiceEventTopic_name, int32(x))
}

func (OrderServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{1}
}

type RetrieveOwnersOrderHistories struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string            `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32             `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderStatus          order.OrderStatus `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3,enum=aggregates.order.OrderStatus" json:"order_status,omitempty"`
	ResultSchema         []byte            `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RetrieveOwnersOrderHistories) Reset()         { *m = RetrieveOwnersOrderHistories{} }
func (m *RetrieveOwnersOrderHistories) String() string { return proto.CompactTextString(m) }
func (*RetrieveOwnersOrderHistories) ProtoMessage()    {}
func (*RetrieveOwnersOrderHistories) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{0}
}

func (m *RetrieveOwnersOrderHistories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Unmarshal(m, b)
}
func (m *RetrieveOwnersOrderHistories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Marshal(b, m, deterministic)
}
func (m *RetrieveOwnersOrderHistories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveOwnersOrderHistories.Merge(m, src)
}
func (m *RetrieveOwnersOrderHistories) XXX_Size() int {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Size(m)
}
func (m *RetrieveOwnersOrderHistories) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveOwnersOrderHistories.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveOwnersOrderHistories proto.InternalMessageInfo

func (m *RetrieveOwnersOrderHistories) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveOwnersOrderHistories) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveOwnersOrderHistories) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveOwnersOrderHistories) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveOwnersOrderHistories) GetOrderStatus() order.OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return order.OrderStatus_PENDING
}

func (m *RetrieveOwnersOrderHistories) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type RetrieveTenantsOrderHistories struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string            `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32             `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderStatus          order.OrderStatus `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3,enum=aggregates.order.OrderStatus" json:"order_status,omitempty"`
	ResultSchema         []byte            `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RetrieveTenantsOrderHistories) Reset()         { *m = RetrieveTenantsOrderHistories{} }
func (m *RetrieveTenantsOrderHistories) String() string { return proto.CompactTextString(m) }
func (*RetrieveTenantsOrderHistories) ProtoMessage()    {}
func (*RetrieveTenantsOrderHistories) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{1}
}

func (m *RetrieveTenantsOrderHistories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Unmarshal(m, b)
}
func (m *RetrieveTenantsOrderHistories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Marshal(b, m, deterministic)
}
func (m *RetrieveTenantsOrderHistories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveTenantsOrderHistories.Merge(m, src)
}
func (m *RetrieveTenantsOrderHistories) XXX_Size() int {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Size(m)
}
func (m *RetrieveTenantsOrderHistories) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveTenantsOrderHistories.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveTenantsOrderHistories proto.InternalMessageInfo

func (m *RetrieveTenantsOrderHistories) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveTenantsOrderHistories) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveTenantsOrderHistories) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveTenantsOrderHistories) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveTenantsOrderHistories) GetOrderStatus() order.OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return order.OrderStatus_PENDING
}

func (m *RetrieveTenantsOrderHistories) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type OwnerReviewTenant struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	OrderUuid            string   `protobuf:"bytes,4,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerReviewTenant) Reset()         { *m = OwnerReviewTenant{} }
func (m *OwnerReviewTenant) String() string { return proto.CompactTextString(m) }
func (*OwnerReviewTenant) ProtoMessage()    {}
func (*OwnerReviewTenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{2}
}

func (m *OwnerReviewTenant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReviewTenant.Unmarshal(m, b)
}
func (m *OwnerReviewTenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReviewTenant.Marshal(b, m, deterministic)
}
func (m *OwnerReviewTenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReviewTenant.Merge(m, src)
}
func (m *OwnerReviewTenant) XXX_Size() int {
	return xxx_messageInfo_OwnerReviewTenant.Size(m)
}
func (m *OwnerReviewTenant) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReviewTenant.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReviewTenant proto.InternalMessageInfo

func (m *OwnerReviewTenant) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerReviewTenant) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *OwnerReviewTenant) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *OwnerReviewTenant) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

type TenantReviewOwner struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	OrderUuid            string   `protobuf:"bytes,4,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantReviewOwner) Reset()         { *m = TenantReviewOwner{} }
func (m *TenantReviewOwner) String() string { return proto.CompactTextString(m) }
func (*TenantReviewOwner) ProtoMessage()    {}
func (*TenantReviewOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{3}
}

func (m *TenantReviewOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewOwner.Unmarshal(m, b)
}
func (m *TenantReviewOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewOwner.Marshal(b, m, deterministic)
}
func (m *TenantReviewOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewOwner.Merge(m, src)
}
func (m *TenantReviewOwner) XXX_Size() int {
	return xxx_messageInfo_TenantReviewOwner.Size(m)
}
func (m *TenantReviewOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewOwner.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewOwner proto.InternalMessageInfo

func (m *TenantReviewOwner) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewOwner) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *TenantReviewOwner) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *TenantReviewOwner) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

type TenantReviewItems struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Review               string   `protobuf:"bytes,4,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantReviewItems) Reset()         { *m = TenantReviewItems{} }
func (m *TenantReviewItems) String() string { return proto.CompactTextString(m) }
func (*TenantReviewItems) ProtoMessage()    {}
func (*TenantReviewItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{4}
}

func (m *TenantReviewItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewItems.Unmarshal(m, b)
}
func (m *TenantReviewItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewItems.Marshal(b, m, deterministic)
}
func (m *TenantReviewItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewItems.Merge(m, src)
}
func (m *TenantReviewItems) XXX_Size() int {
	return xxx_messageInfo_TenantReviewItems.Size(m)
}
func (m *TenantReviewItems) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewItems.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewItems proto.InternalMessageInfo

func (m *TenantReviewItems) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewItems) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *TenantReviewItems) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *TenantReviewItems) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type ApproveOrder struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OrderUuid            string   `protobuf:"bytes,3,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveOrder) Reset()         { *m = ApproveOrder{} }
func (m *ApproveOrder) String() string { return proto.CompactTextString(m) }
func (*ApproveOrder) ProtoMessage()    {}
func (*ApproveOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{5}
}

func (m *ApproveOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveOrder.Unmarshal(m, b)
}
func (m *ApproveOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveOrder.Marshal(b, m, deterministic)
}
func (m *ApproveOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveOrder.Merge(m, src)
}
func (m *ApproveOrder) XXX_Size() int {
	return xxx_messageInfo_ApproveOrder.Size(m)
}
func (m *ApproveOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveOrder proto.InternalMessageInfo

func (m *ApproveOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ApproveOrder) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *ApproveOrder) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

type DisapproveOrder struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OrderUuid            string   `protobuf:"bytes,3,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisapproveOrder) Reset()         { *m = DisapproveOrder{} }
func (m *DisapproveOrder) String() string { return proto.CompactTextString(m) }
func (*DisapproveOrder) ProtoMessage()    {}
func (*DisapproveOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{6}
}

func (m *DisapproveOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisapproveOrder.Unmarshal(m, b)
}
func (m *DisapproveOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisapproveOrder.Marshal(b, m, deterministic)
}
func (m *DisapproveOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisapproveOrder.Merge(m, src)
}
func (m *DisapproveOrder) XXX_Size() int {
	return xxx_messageInfo_DisapproveOrder.Size(m)
}
func (m *DisapproveOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DisapproveOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DisapproveOrder proto.InternalMessageInfo

func (m *DisapproveOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DisapproveOrder) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *DisapproveOrder) GetOrderUuid() string {
	if m != nil {
		return m.OrderUuid
	}
	return ""
}

type OwnersOrderHistoriesRetrieved struct {
	Uid                          string                        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus                  *Status                       `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RetrieveOwnersOrderHistories *RetrieveOwnersOrderHistories `protobuf:"bytes,3,opt,name=retrieve_owners_order_histories,json=retrieveOwnersOrderHistories,proto3" json:"retrieve_owners_order_histories,omitempty"`
	Result                       []byte                        `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	XXX_unrecognized             []byte                        `json:"-"`
	XXX_sizecache                int32                         `json:"-"`
}

func (m *OwnersOrderHistoriesRetrieved) Reset()         { *m = OwnersOrderHistoriesRetrieved{} }
func (m *OwnersOrderHistoriesRetrieved) String() string { return proto.CompactTextString(m) }
func (*OwnersOrderHistoriesRetrieved) ProtoMessage()    {}
func (*OwnersOrderHistoriesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{7}
}

func (m *OwnersOrderHistoriesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Unmarshal(m, b)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Marshal(b, m, deterministic)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnersOrderHistoriesRetrieved.Merge(m, src)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Size() int {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Size(m)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnersOrderHistoriesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_OwnersOrderHistoriesRetrieved proto.InternalMessageInfo

func (m *OwnersOrderHistoriesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnersOrderHistoriesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetRetrieveOwnersOrderHistories() *RetrieveOwnersOrderHistories {
	if m != nil {
		return m.RetrieveOwnersOrderHistories
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type TenantOrderHistoriesRetrieved struct {
	Uid                           string                         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant                        *user.User                     `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus                   *Status                        `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RetrieveTenantsOrderHistories *RetrieveTenantsOrderHistories `protobuf:"bytes,5,opt,name=retrieve_tenants_order_histories,json=retrieveTenantsOrderHistories,proto3" json:"retrieve_tenants_order_histories,omitempty"`
	Result                        []byte                         `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                       `json:"-"`
	XXX_unrecognized              []byte                         `json:"-"`
	XXX_sizecache                 int32                          `json:"-"`
}

func (m *TenantOrderHistoriesRetrieved) Reset()         { *m = TenantOrderHistoriesRetrieved{} }
func (m *TenantOrderHistoriesRetrieved) String() string { return proto.CompactTextString(m) }
func (*TenantOrderHistoriesRetrieved) ProtoMessage()    {}
func (*TenantOrderHistoriesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{8}
}

func (m *TenantOrderHistoriesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Unmarshal(m, b)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Marshal(b, m, deterministic)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantOrderHistoriesRetrieved.Merge(m, src)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Size() int {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Size(m)
}
func (m *TenantOrderHistoriesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantOrderHistoriesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_TenantOrderHistoriesRetrieved proto.InternalMessageInfo

func (m *TenantOrderHistoriesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantOrderHistoriesRetrieved) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetRetrieveTenantsOrderHistories() *RetrieveTenantsOrderHistories {
	if m != nil {
		return m.RetrieveTenantsOrderHistories
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type OwnerReviewedTenant struct {
	Uid                  string             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User         `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Tenant               *user.User         `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status            `protobuf:"bytes,4,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Order                *order.Order       `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	OwnerReviewTenant    *OwnerReviewTenant `protobuf:"bytes,6,opt,name=owner_review_tenant,json=ownerReviewTenant,proto3" json:"owner_review_tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OwnerReviewedTenant) Reset()         { *m = OwnerReviewedTenant{} }
func (m *OwnerReviewedTenant) String() string { return proto.CompactTextString(m) }
func (*OwnerReviewedTenant) ProtoMessage()    {}
func (*OwnerReviewedTenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{9}
}

func (m *OwnerReviewedTenant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReviewedTenant.Unmarshal(m, b)
}
func (m *OwnerReviewedTenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReviewedTenant.Marshal(b, m, deterministic)
}
func (m *OwnerReviewedTenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReviewedTenant.Merge(m, src)
}
func (m *OwnerReviewedTenant) XXX_Size() int {
	return xxx_messageInfo_OwnerReviewedTenant.Size(m)
}
func (m *OwnerReviewedTenant) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReviewedTenant.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReviewedTenant proto.InternalMessageInfo

func (m *OwnerReviewedTenant) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerReviewedTenant) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OwnerReviewedTenant) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *OwnerReviewedTenant) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnerReviewedTenant) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OwnerReviewedTenant) GetOwnerReviewTenant() *OwnerReviewTenant {
	if m != nil {
		return m.OwnerReviewTenant
	}
	return nil
}

type TenantReviewedOwner struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User           `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Owner                *user.User           `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status              `protobuf:"bytes,4,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerFeedback        *order.OwnerFeedback `protobuf:"bytes,5,opt,name=owner_feedback,json=ownerFeedback,proto3" json:"owner_feedback,omitempty"`
	TenantReviewOwner    *TenantReviewOwner   `protobuf:"bytes,6,opt,name=tenant_review_owner,json=tenantReviewOwner,proto3" json:"tenant_review_owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TenantReviewedOwner) Reset()         { *m = TenantReviewedOwner{} }
func (m *TenantReviewedOwner) String() string { return proto.CompactTextString(m) }
func (*TenantReviewedOwner) ProtoMessage()    {}
func (*TenantReviewedOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{10}
}

func (m *TenantReviewedOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewedOwner.Unmarshal(m, b)
}
func (m *TenantReviewedOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewedOwner.Marshal(b, m, deterministic)
}
func (m *TenantReviewedOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewedOwner.Merge(m, src)
}
func (m *TenantReviewedOwner) XXX_Size() int {
	return xxx_messageInfo_TenantReviewedOwner.Size(m)
}
func (m *TenantReviewedOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewedOwner.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewedOwner proto.InternalMessageInfo

func (m *TenantReviewedOwner) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewedOwner) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantReviewedOwner) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *TenantReviewedOwner) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantReviewedOwner) GetOwnerFeedback() *order.OwnerFeedback {
	if m != nil {
		return m.OwnerFeedback
	}
	return nil
}

func (m *TenantReviewedOwner) GetTenantReviewOwner() *TenantReviewOwner {
	if m != nil {
		return m.TenantReviewOwner
	}
	return nil
}

type TenantReviewedItems struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	ItemFeedback         *order.ItemFeedback `protobuf:"bytes,4,opt,name=item_feedback,json=itemFeedback,proto3" json:"item_feedback,omitempty"`
	TenantReviewItems    *TenantReviewItems  `protobuf:"bytes,5,opt,name=tenant_review_items,json=tenantReviewItems,proto3" json:"tenant_review_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TenantReviewedItems) Reset()         { *m = TenantReviewedItems{} }
func (m *TenantReviewedItems) String() string { return proto.CompactTextString(m) }
func (*TenantReviewedItems) ProtoMessage()    {}
func (*TenantReviewedItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{11}
}

func (m *TenantReviewedItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewedItems.Unmarshal(m, b)
}
func (m *TenantReviewedItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewedItems.Marshal(b, m, deterministic)
}
func (m *TenantReviewedItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewedItems.Merge(m, src)
}
func (m *TenantReviewedItems) XXX_Size() int {
	return xxx_messageInfo_TenantReviewedItems.Size(m)
}
func (m *TenantReviewedItems) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewedItems.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewedItems proto.InternalMessageInfo

func (m *TenantReviewedItems) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewedItems) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantReviewedItems) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantReviewedItems) GetItemFeedback() *order.ItemFeedback {
	if m != nil {
		return m.ItemFeedback
	}
	return nil
}

func (m *TenantReviewedItems) GetTenantReviewItems() *TenantReviewItems {
	if m != nil {
		return m.TenantReviewItems
	}
	return nil
}

type OrderApproved struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User    `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status       `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Order                *order.Order  `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	ApproveOrder         *ApproveOrder `protobuf:"bytes,5,opt,name=approve_order,json=approveOrder,proto3" json:"approve_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderApproved) Reset()         { *m = OrderApproved{} }
func (m *OrderApproved) String() string { return proto.CompactTextString(m) }
func (*OrderApproved) ProtoMessage()    {}
func (*OrderApproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{12}
}

func (m *OrderApproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderApproved.Unmarshal(m, b)
}
func (m *OrderApproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderApproved.Marshal(b, m, deterministic)
}
func (m *OrderApproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderApproved.Merge(m, src)
}
func (m *OrderApproved) XXX_Size() int {
	return xxx_messageInfo_OrderApproved.Size(m)
}
func (m *OrderApproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderApproved.DiscardUnknown(m)
}

var xxx_messageInfo_OrderApproved proto.InternalMessageInfo

func (m *OrderApproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrderApproved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OrderApproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrderApproved) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OrderApproved) GetApproveOrder() *ApproveOrder {
	if m != nil {
		return m.ApproveOrder
	}
	return nil
}

type OrderDisapproved struct {
	Uid                  string           `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status          `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Order                *order.Order     `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	DisapproveOrder      *DisapproveOrder `protobuf:"bytes,5,opt,name=disapprove_order,json=disapproveOrder,proto3" json:"disapprove_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderDisapproved) Reset()         { *m = OrderDisapproved{} }
func (m *OrderDisapproved) String() string { return proto.CompactTextString(m) }
func (*OrderDisapproved) ProtoMessage()    {}
func (*OrderDisapproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{13}
}

func (m *OrderDisapproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDisapproved.Unmarshal(m, b)
}
func (m *OrderDisapproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDisapproved.Marshal(b, m, deterministic)
}
func (m *OrderDisapproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDisapproved.Merge(m, src)
}
func (m *OrderDisapproved) XXX_Size() int {
	return xxx_messageInfo_OrderDisapproved.Size(m)
}
func (m *OrderDisapproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDisapproved.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDisapproved proto.InternalMessageInfo

func (m *OrderDisapproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrderDisapproved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OrderDisapproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrderDisapproved) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OrderDisapproved) GetDisapproveOrder() *DisapproveOrder {
	if m != nil {
		return m.DisapproveOrder
	}
	return nil
}

func init() {
	proto.RegisterEnum("event.OrderServiceCommandTopic", OrderServiceCommandTopic_name, OrderServiceCommandTopic_value)
	proto.RegisterEnum("event.OrderServiceEventTopic", OrderServiceEventTopic_name, OrderServiceEventTopic_value)
	proto.RegisterType((*RetrieveOwnersOrderHistories)(nil), "event.RetrieveOwnersOrderHistories")
	proto.RegisterType((*RetrieveTenantsOrderHistories)(nil), "event.RetrieveTenantsOrderHistories")
	proto.RegisterType((*OwnerReviewTenant)(nil), "event.OwnerReviewTenant")
	proto.RegisterType((*TenantReviewOwner)(nil), "event.TenantReviewOwner")
	proto.RegisterType((*TenantReviewItems)(nil), "event.TenantReviewItems")
	proto.RegisterType((*ApproveOrder)(nil), "event.ApproveOrder")
	proto.RegisterType((*DisapproveOrder)(nil), "event.DisapproveOrder")
	proto.RegisterType((*OwnersOrderHistoriesRetrieved)(nil), "event.OwnersOrderHistoriesRetrieved")
	proto.RegisterType((*TenantOrderHistoriesRetrieved)(nil), "event.TenantOrderHistoriesRetrieved")
	proto.RegisterType((*OwnerReviewedTenant)(nil), "event.OwnerReviewedTenant")
	proto.RegisterType((*TenantReviewedOwner)(nil), "event.TenantReviewedOwner")
	proto.RegisterType((*TenantReviewedItems)(nil), "event.TenantReviewedItems")
	proto.RegisterType((*OrderApproved)(nil), "event.OrderApproved")
	proto.RegisterType((*OrderDisapproved)(nil), "event.OrderDisapproved")
}

func init() { proto.RegisterFile("events/order.proto", fileDescriptor_8148e438de8b220f) }

var fileDescriptor_8148e438de8b220f = []byte{
	// 1009 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0xf5, 0x07, 0x64, 0x44, 0x39, 0xd4, 0x2a, 0x76, 0x14, 0xc3, 0xaa, 0x15, 0xd9, 0x01,
	0x8c, 0x14, 0x92, 0x0b, 0xf7, 0xd2, 0x4b, 0xd1, 0xba, 0x11, 0x03, 0xeb, 0x50, 0x2b, 0x58, 0x29,
	0x09, 0xd0, 0x0b, 0x41, 0x8b, 0x6b, 0x89, 0xb5, 0x29, 0x1a, 0xe4, 0x52, 0xe9, 0xad, 0x8f, 0x51,
	0xf4, 0x25, 0xfa, 0x1a, 0x7d, 0x86, 0x1e, 0x7b, 0x6a, 0xfb, 0x00, 0xbd, 0x17, 0x3b, 0xbb, 0x94,
	0x48, 0x51, 0x72, 0x6c, 0xb7, 0x2e, 0x8a, 0x5e, 0x04, 0xcd, 0xec, 0xec, 0xcc, 0x7c, 0xdf, 0xee,
	0xcc, 0x2c, 0x81, 0xb0, 0x19, 0x9b, 0xf2, 0xf0, 0xd0, 0x0f, 0x1c, 0x16, 0x74, 0xae, 0x02, 0x9f,
	0xfb, 0xa4, 0x88, 0xba, 0xed, 0x1d, 0x7b, 0x3c, 0x0e, 0xd8, 0xd8, 0xe6, 0x4c, 0x2d, 0x27, 0x8d,
	0xb6, 0x6b, 0x6a, 0x63, 0xc8, 0x6d, 0x1e, 0x85, 0x4a, 0xb9, 0x9d, 0xd8, 0x12, 0x85, 0x2c, 0xc0,
	0x1f, 0xb5, 0xf6, 0x3c, 0xeb, 0xee, 0xfd, 0x94, 0x05, 0xd6, 0x39, 0x63, 0xce, 0x99, 0x3d, 0xba,
	0x50, 0x66, 0xfb, 0x19, 0x33, 0x97, 0x33, 0x6f, 0xc9, 0xaa, 0xf5, 0xbb, 0x06, 0x3b, 0x94, 0xf1,
	0xc0, 0x65, 0x33, 0xd6, 0x17, 0x6e, 0xc2, 0xbe, 0xb0, 0x3d, 0x71, 0x43, 0xee, 0x07, 0x2e, 0x0b,
	0x89, 0x01, 0xf9, 0xc8, 0x75, 0xea, 0x5a, 0x53, 0x3b, 0x78, 0x48, 0xc5, 0x5f, 0xf2, 0x0c, 0xf4,
	0x8b, 0xc8, 0xb1, 0x2f, 0x5c, 0x8b, 0xfb, 0x17, 0x6c, 0x5a, 0xcf, 0xe1, 0x52, 0x59, 0xea, 0x86,
	0x42, 0x45, 0xb6, 0xa0, 0xe4, 0x9f, 0x9f, 0x87, 0x8c, 0xd7, 0xf3, 0x4d, 0xed, 0xa0, 0x48, 0x95,
	0x44, 0x1e, 0x43, 0xf1, 0xd2, 0xf5, 0x5c, 0x5e, 0x2f, 0xa0, 0x5a, 0x0a, 0xe4, 0x4b, 0xd0, 0x31,
	0x41, 0x4b, 0x52, 0x50, 0x2f, 0x36, 0xb5, 0x83, 0x8d, 0xa3, 0x46, 0x67, 0x01, 0xa0, 0x23, 0x09,
	0xc3, 0xd4, 0x06, 0x68, 0x44, 0xcb, 0xfe, 0x42, 0x20, 0x7b, 0x50, 0x09, 0x58, 0x18, 0x5d, 0x72,
	0x2b, 0x1c, 0x4d, 0x98, 0x67, 0xd7, 0x4b, 0x4d, 0xed, 0x40, 0xa7, 0xba, 0x54, 0x0e, 0x50, 0xd7,
	0xfa, 0x43, 0x83, 0x46, 0x0c, 0x75, 0xc8, 0xa6, 0xf6, 0x94, 0xff, 0x7f, 0xb1, 0x7e, 0x0f, 0x55,
	0x3c, 0x4d, 0xca, 0x66, 0x2e, 0x7b, 0x2f, 0xd1, 0xde, 0x19, 0x5e, 0x60, 0x73, 0x77, 0x3a, 0x46,
	0x78, 0x39, 0xaa, 0x24, 0xd2, 0x00, 0x90, 0x40, 0x22, 0xe1, 0xb3, 0x80, 0x1b, 0x1f, 0xa2, 0xe6,
	0x4d, 0xe4, 0x3a, 0x22, 0x01, 0x19, 0x55, 0x66, 0x80, 0xc9, 0xfc, 0xab, 0x09, 0x7c, 0x97, 0x4e,
	0xa0, 0xc7, 0x99, 0x17, 0xfe, 0xb3, 0x09, 0x08, 0x3d, 0xfa, 0x56, 0xc1, 0x95, 0xd4, 0x3a, 0x03,
	0xfd, 0xf8, 0xea, 0x2a, 0xf0, 0x67, 0x0c, 0xcf, 0xf0, 0x6e, 0x41, 0xd3, 0xe8, 0xf2, 0xcb, 0xe8,
	0x18, 0x3c, 0xea, 0xba, 0xa1, 0x7d, 0xdf, 0x61, 0x7e, 0xd3, 0xa0, 0xb1, 0xaa, 0x2b, 0xc4, 0x65,
	0xe4, 0xac, 0x88, 0xfa, 0x09, 0xe8, 0xd8, 0xd1, 0xe2, 0x1b, 0x2e, 0xa2, 0x96, 0x8f, 0x2a, 0x1d,
	0x54, 0x76, 0xe2, 0x1b, 0x8d, 0x92, 0xba, 0xd1, 0xdf, 0xc2, 0x6e, 0xa0, 0x1c, 0x5a, 0xd8, 0xca,
	0x42, 0x4b, 0x26, 0x35, 0x89, 0xe3, 0x61, 0x66, 0xe5, 0xa3, 0x3d, 0xe5, 0xe4, 0xba, 0x86, 0x45,
	0x77, 0x82, 0xeb, 0xda, 0x19, 0x1e, 0x9a, 0x28, 0x14, 0x3c, 0x34, 0x9d, 0x2a, 0xa9, 0xf5, 0x63,
	0x0e, 0x1a, 0xf2, 0xbe, 0xdc, 0x1c, 0x69, 0x1b, 0x4a, 0x1c, 0xb7, 0x28, 0x8c, 0x9b, 0xc9, 0x2a,
	0xc6, 0x86, 0xfd, 0x26, 0x64, 0x01, 0x55, 0x46, 0x19, 0x62, 0xf2, 0x1f, 0x24, 0xc6, 0x83, 0xe6,
	0x9c, 0x18, 0xe9, 0x24, 0xcb, 0x4c, 0x11, 0xbd, 0xec, 0x2f, 0x31, 0xb3, 0xb2, 0xbf, 0xd1, 0x46,
	0x70, 0x6d, 0xfb, 0x5b, 0xc7, 0xcd, 0x4f, 0x39, 0xa8, 0x25, 0xba, 0x09, 0x73, 0xd6, 0xf6, 0x93,
	0x8f, 0xa1, 0x88, 0x07, 0x78, 0x3d, 0x21, 0xd2, 0x26, 0x41, 0x5f, 0xfe, 0x2e, 0xf4, 0x15, 0x3e,
	0x48, 0x5f, 0x1b, 0x8a, 0xc8, 0x96, 0xe2, 0xe8, 0xc9, 0x9a, 0x26, 0x4b, 0xa5, 0x15, 0x39, 0x81,
	0x9a, 0x1c, 0xa4, 0xb2, 0x8e, 0x15, 0xe3, 0xd8, 0x5e, 0xcb, 0x47, 0x75, 0x15, 0x27, 0xd3, 0x55,
	0x69, 0xd5, 0x5f, 0x56, 0xb5, 0x7e, 0xce, 0x41, 0x2d, 0xd9, 0x7c, 0x98, 0xb3, 0xae, 0xff, 0xdd,
	0xf2, 0x0a, 0xcd, 0xf9, 0xcd, 0xdf, 0x80, 0xdf, 0xdb, 0x13, 0xf6, 0x0a, 0x36, 0xd2, 0x4f, 0x09,
	0xc5, 0xdc, 0xee, 0x0a, 0xe6, 0x84, 0xdd, 0x2b, 0x65, 0x46, 0x2b, 0x7e, 0x52, 0x14, 0x4c, 0xca,
	0x84, 0x63, 0x2a, 0x65, 0xd2, 0x69, 0x26, 0x33, 0xe3, 0x81, 0x56, 0xf9, 0xb2, 0xaa, 0xf5, 0x43,
	0x86, 0xc9, 0x75, 0x8d, 0xfc, 0xde, 0x8b, 0xf1, 0x25, 0x54, 0x52, 0x0f, 0x28, 0xc5, 0xe7, 0x47,
	0x59, 0x6e, 0x44, 0x8a, 0x73, 0x6a, 0x74, 0x37, 0x21, 0x65, 0x99, 0x11, 0xab, 0x71, 0x11, 0xaf,
	0x62, 0x06, 0xe1, 0xa6, 0x99, 0x41, 0x95, 0x78, 0xcd, 0x54, 0xf0, 0xfa, 0xaa, 0x59, 0xe3, 0xfc,
	0xdd, 0x72, 0xbc, 0x3d, 0x23, 0xf3, 0xfa, 0x2a, 0xdc, 0xa8, 0xbe, 0x3e, 0x83, 0x8a, 0x1a, 0x58,
	0x56, 0xb2, 0x2c, 0x6b, 0x2a, 0x42, 0x72, 0x66, 0x52, 0x3d, 0x39, 0xda, 0x5a, 0x7f, 0x6a, 0x60,
	0xe0, 0xbf, 0xc5, 0xcc, 0xfb, 0xef, 0xc3, 0x3d, 0x06, 0xc3, 0x99, 0xa7, 0x9b, 0x42, 0xbc, 0xa5,
	0x82, 0x2c, 0x4d, 0x70, 0xfa, 0xc8, 0x49, 0x2b, 0x5e, 0xfc, 0xa2, 0x41, 0x5d, 0xbe, 0x03, 0x59,
	0x30, 0x73, 0x47, 0xec, 0xa5, 0xef, 0x79, 0xf6, 0xd4, 0x19, 0xfa, 0x57, 0xee, 0x88, 0xec, 0xc1,
	0x2e, 0x35, 0x87, 0xb4, 0x67, 0xbe, 0x35, 0xad, 0xfe, 0xbb, 0x53, 0x93, 0x0e, 0xac, 0x3e, 0xed,
	0x9a, 0xd4, 0x3a, 0xe9, 0x0d, 0x86, 0x7d, 0xda, 0x33, 0x07, 0xc6, 0x03, 0xb2, 0x0f, 0xcd, 0xb9,
	0xd1, 0xd0, 0x3c, 0x3d, 0x3e, 0x1d, 0x66, 0xad, 0x34, 0xf2, 0x04, 0x6a, 0xe8, 0xc1, 0xa2, 0xe6,
	0xdb, 0x9e, 0xf9, 0x4e, 0x59, 0x1a, 0x39, 0xb1, 0x20, 0xff, 0xc7, 0x2b, 0x68, 0x66, 0xe4, 0xb3,
	0x0b, 0xbd, 0xa1, 0xf9, 0xf5, 0xc0, 0x28, 0x90, 0x2a, 0x54, 0x8e, 0x5f, 0xbf, 0xa6, 0x7d, 0x91,
	0x94, 0x88, 0x63, 0x14, 0xc9, 0x63, 0x30, 0xba, 0xbd, 0x41, 0x5a, 0x5b, 0x7a, 0xf1, 0xab, 0x06,
	0x5b, 0x49, 0x6c, 0xa6, 0xa0, 0x44, 0x22, 0xdb, 0x87, 0xe6, 0x6a, 0x40, 0x56, 0x8c, 0xa5, 0x6b,
	0x3c, 0x20, 0xcf, 0xe1, 0xd9, 0x1a, 0x44, 0x09, 0x33, 0x8d, 0x3c, 0x85, 0xcd, 0x24, 0x36, 0xb3,
	0xbb, 0x40, 0xf7, 0x14, 0x36, 0x53, 0x20, 0xcc, 0xee, 0x1c, 0xdf, 0x8a, 0xa5, 0x18, 0x21, 0x81,
	0x0d, 0x19, 0x4f, 0x21, 0xea, 0x1a, 0x45, 0xb2, 0x09, 0x55, 0xa9, 0x5b, 0x00, 0xed, 0x1a, 0xa5,
	0xaf, 0xbe, 0xf8, 0xe6, 0xf3, 0xb1, 0xcb, 0x27, 0xd1, 0x59, 0x67, 0xe4, 0x7b, 0x87, 0xee, 0xe5,
	0xc4, 0xf6, 0xbc, 0x89, 0xe3, 0x1c, 0xca, 0x17, 0x58, 0x5b, 0xdc, 0xc9, 0xb6, 0x1d, 0xf1, 0x49,
	0x3b, 0x94, 0x1c, 0x88, 0xaf, 0xbc, 0x91, 0x1d, 0xb2, 0xf0, 0x50, 0x7e, 0x13, 0x9e, 0x95, 0xf0,
	0x23, 0xed, 0xd3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x65, 0xde, 0x5c, 0x5d, 0x0e, 0x00,
	0x00,
}
