// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events/order.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	order "github.com/ilhammhdd/kudaki-mountain-service/entities/aggregates/order"
	user "github.com/ilhammhdd/kudaki-mountain-service/entities/aggregates/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//order service commands
type OrderServiceCommandTopic int32

const (
	OrderServiceCommandTopic_RETRIEVE_OWNERS_ORDER_HISTORIES  OrderServiceCommandTopic = 0
	OrderServiceCommandTopic_RETRIEVE_TENANTS_ORDER_HISTORIES OrderServiceCommandTopic = 1
	OrderServiceCommandTopic_TENANT_REVIEW_OWNER_ORDER        OrderServiceCommandTopic = 2
	OrderServiceCommandTopic_APPROVE_OWNER_ORDER              OrderServiceCommandTopic = 5
	OrderServiceCommandTopic_DISAPPROVE_OWNER_ORDER           OrderServiceCommandTopic = 6
	OrderServiceCommandTopic_CHECK_OUT                        OrderServiceCommandTopic = 7
	OrderServiceCommandTopic_OWNER_CONFIRM_RETURNMENT         OrderServiceCommandTopic = 8
)

var OrderServiceCommandTopic_name = map[int32]string{
	0: "RETRIEVE_OWNERS_ORDER_HISTORIES",
	1: "RETRIEVE_TENANTS_ORDER_HISTORIES",
	2: "TENANT_REVIEW_OWNER_ORDER",
	5: "APPROVE_OWNER_ORDER",
	6: "DISAPPROVE_OWNER_ORDER",
	7: "CHECK_OUT",
	8: "OWNER_CONFIRM_RETURNMENT",
}

var OrderServiceCommandTopic_value = map[string]int32{
	"RETRIEVE_OWNERS_ORDER_HISTORIES":  0,
	"RETRIEVE_TENANTS_ORDER_HISTORIES": 1,
	"TENANT_REVIEW_OWNER_ORDER":        2,
	"APPROVE_OWNER_ORDER":              5,
	"DISAPPROVE_OWNER_ORDER":           6,
	"CHECK_OUT":                        7,
	"OWNER_CONFIRM_RETURNMENT":         8,
}

func (x OrderServiceCommandTopic) String() string {
	return proto.EnumName(OrderServiceCommandTopic_name, int32(x))
}

func (OrderServiceCommandTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{0}
}

//
//order service events
type OrderServiceEventTopic int32

const (
	OrderServiceEventTopic_OWNERS_ORDER_HISTORIES_RETRIEVED  OrderServiceEventTopic = 0
	OrderServiceEventTopic_TENANTS_ORDER_HISTORIES_RETRIEVED OrderServiceEventTopic = 1
	OrderServiceEventTopic_TENANT_REVIEWED_OWNER_ORDER       OrderServiceEventTopic = 2
	OrderServiceEventTopic_OWNER_ORDER_APPROVED              OrderServiceEventTopic = 5
	OrderServiceEventTopic_OWNER_ORDER_DISAPPROVED           OrderServiceEventTopic = 6
	OrderServiceEventTopic_CHECKED_OUT                       OrderServiceEventTopic = 7
	OrderServiceEventTopic_ORDER_APPROVED                    OrderServiceEventTopic = 8
	OrderServiceEventTopic_ORDER_DISAPPROVED                 OrderServiceEventTopic = 9
	OrderServiceEventTopic_OWNER_CONFIRMED_RETURNMENT        OrderServiceEventTopic = 10
)

var OrderServiceEventTopic_name = map[int32]string{
	0:  "OWNERS_ORDER_HISTORIES_RETRIEVED",
	1:  "TENANTS_ORDER_HISTORIES_RETRIEVED",
	2:  "TENANT_REVIEWED_OWNER_ORDER",
	5:  "OWNER_ORDER_APPROVED",
	6:  "OWNER_ORDER_DISAPPROVED",
	7:  "CHECKED_OUT",
	8:  "ORDER_APPROVED",
	9:  "ORDER_DISAPPROVED",
	10: "OWNER_CONFIRMED_RETURNMENT",
}

var OrderServiceEventTopic_value = map[string]int32{
	"OWNERS_ORDER_HISTORIES_RETRIEVED":  0,
	"TENANTS_ORDER_HISTORIES_RETRIEVED": 1,
	"TENANT_REVIEWED_OWNER_ORDER":       2,
	"OWNER_ORDER_APPROVED":              5,
	"OWNER_ORDER_DISAPPROVED":           6,
	"CHECKED_OUT":                       7,
	"ORDER_APPROVED":                    8,
	"ORDER_DISAPPROVED":                 9,
	"OWNER_CONFIRMED_RETURNMENT":        10,
}

func (x OrderServiceEventTopic) String() string {
	return proto.EnumName(OrderServiceEventTopic_name, int32(x))
}

func (OrderServiceEventTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{1}
}

type RetrieveOwnersOrderHistories struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string            `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32             `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderStatus          order.OrderStatus `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3,enum=aggregates.order.OrderStatus" json:"order_status,omitempty"`
	ResultSchema         []byte            `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RetrieveOwnersOrderHistories) Reset()         { *m = RetrieveOwnersOrderHistories{} }
func (m *RetrieveOwnersOrderHistories) String() string { return proto.CompactTextString(m) }
func (*RetrieveOwnersOrderHistories) ProtoMessage()    {}
func (*RetrieveOwnersOrderHistories) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{0}
}

func (m *RetrieveOwnersOrderHistories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Unmarshal(m, b)
}
func (m *RetrieveOwnersOrderHistories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Marshal(b, m, deterministic)
}
func (m *RetrieveOwnersOrderHistories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveOwnersOrderHistories.Merge(m, src)
}
func (m *RetrieveOwnersOrderHistories) XXX_Size() int {
	return xxx_messageInfo_RetrieveOwnersOrderHistories.Size(m)
}
func (m *RetrieveOwnersOrderHistories) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveOwnersOrderHistories.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveOwnersOrderHistories proto.InternalMessageInfo

func (m *RetrieveOwnersOrderHistories) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveOwnersOrderHistories) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveOwnersOrderHistories) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveOwnersOrderHistories) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveOwnersOrderHistories) GetOrderStatus() order.OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return order.OrderStatus_PENDING
}

func (m *RetrieveOwnersOrderHistories) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type RetrieveTenantsOrderHistories struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string            `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	Offset               int32             `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32             `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderStatus          order.OrderStatus `protobuf:"varint,5,opt,name=order_status,json=orderStatus,proto3,enum=aggregates.order.OrderStatus" json:"order_status,omitempty"`
	ResultSchema         []byte            `protobuf:"bytes,6,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RetrieveTenantsOrderHistories) Reset()         { *m = RetrieveTenantsOrderHistories{} }
func (m *RetrieveTenantsOrderHistories) String() string { return proto.CompactTextString(m) }
func (*RetrieveTenantsOrderHistories) ProtoMessage()    {}
func (*RetrieveTenantsOrderHistories) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{1}
}

func (m *RetrieveTenantsOrderHistories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Unmarshal(m, b)
}
func (m *RetrieveTenantsOrderHistories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Marshal(b, m, deterministic)
}
func (m *RetrieveTenantsOrderHistories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveTenantsOrderHistories.Merge(m, src)
}
func (m *RetrieveTenantsOrderHistories) XXX_Size() int {
	return xxx_messageInfo_RetrieveTenantsOrderHistories.Size(m)
}
func (m *RetrieveTenantsOrderHistories) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveTenantsOrderHistories.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveTenantsOrderHistories proto.InternalMessageInfo

func (m *RetrieveTenantsOrderHistories) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RetrieveTenantsOrderHistories) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *RetrieveTenantsOrderHistories) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RetrieveTenantsOrderHistories) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RetrieveTenantsOrderHistories) GetOrderStatus() order.OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return order.OrderStatus_PENDING
}

func (m *RetrieveTenantsOrderHistories) GetResultSchema() []byte {
	if m != nil {
		return m.ResultSchema
	}
	return nil
}

type ApproveOwnerOrder struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OwnerOrderUuid       string   `protobuf:"bytes,3,opt,name=owner_order_uuid,json=ownerOrderUuid,proto3" json:"owner_order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveOwnerOrder) Reset()         { *m = ApproveOwnerOrder{} }
func (m *ApproveOwnerOrder) String() string { return proto.CompactTextString(m) }
func (*ApproveOwnerOrder) ProtoMessage()    {}
func (*ApproveOwnerOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{2}
}

func (m *ApproveOwnerOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveOwnerOrder.Unmarshal(m, b)
}
func (m *ApproveOwnerOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveOwnerOrder.Marshal(b, m, deterministic)
}
func (m *ApproveOwnerOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveOwnerOrder.Merge(m, src)
}
func (m *ApproveOwnerOrder) XXX_Size() int {
	return xxx_messageInfo_ApproveOwnerOrder.Size(m)
}
func (m *ApproveOwnerOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveOwnerOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveOwnerOrder proto.InternalMessageInfo

func (m *ApproveOwnerOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ApproveOwnerOrder) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *ApproveOwnerOrder) GetOwnerOrderUuid() string {
	if m != nil {
		return m.OwnerOrderUuid
	}
	return ""
}

type DisapproveOwnerOrder struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OwnerOrderUuid       string   `protobuf:"bytes,3,opt,name=owner_order_uuid,json=ownerOrderUuid,proto3" json:"owner_order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisapproveOwnerOrder) Reset()         { *m = DisapproveOwnerOrder{} }
func (m *DisapproveOwnerOrder) String() string { return proto.CompactTextString(m) }
func (*DisapproveOwnerOrder) ProtoMessage()    {}
func (*DisapproveOwnerOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{3}
}

func (m *DisapproveOwnerOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisapproveOwnerOrder.Unmarshal(m, b)
}
func (m *DisapproveOwnerOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisapproveOwnerOrder.Marshal(b, m, deterministic)
}
func (m *DisapproveOwnerOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisapproveOwnerOrder.Merge(m, src)
}
func (m *DisapproveOwnerOrder) XXX_Size() int {
	return xxx_messageInfo_DisapproveOwnerOrder.Size(m)
}
func (m *DisapproveOwnerOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DisapproveOwnerOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DisapproveOwnerOrder proto.InternalMessageInfo

func (m *DisapproveOwnerOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DisapproveOwnerOrder) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *DisapproveOwnerOrder) GetOwnerOrderUuid() string {
	if m != nil {
		return m.OwnerOrderUuid
	}
	return ""
}

type CheckOut struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	CartUuid             string   `protobuf:"bytes,3,opt,name=cart_uuid,json=cartUuid,proto3" json:"cart_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckOut) Reset()         { *m = CheckOut{} }
func (m *CheckOut) String() string { return proto.CompactTextString(m) }
func (*CheckOut) ProtoMessage()    {}
func (*CheckOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{4}
}

func (m *CheckOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckOut.Unmarshal(m, b)
}
func (m *CheckOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckOut.Marshal(b, m, deterministic)
}
func (m *CheckOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckOut.Merge(m, src)
}
func (m *CheckOut) XXX_Size() int {
	return xxx_messageInfo_CheckOut.Size(m)
}
func (m *CheckOut) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckOut.DiscardUnknown(m)
}

var xxx_messageInfo_CheckOut proto.InternalMessageInfo

func (m *CheckOut) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CheckOut) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *CheckOut) GetCartUuid() string {
	if m != nil {
		return m.CartUuid
	}
	return ""
}

type OwnerConfirmReturnment struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OwnerOrderUuid       string   `protobuf:"bytes,3,opt,name=owner_order_uuid,json=ownerOrderUuid,proto3" json:"owner_order_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnerConfirmReturnment) Reset()         { *m = OwnerConfirmReturnment{} }
func (m *OwnerConfirmReturnment) String() string { return proto.CompactTextString(m) }
func (*OwnerConfirmReturnment) ProtoMessage()    {}
func (*OwnerConfirmReturnment) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{5}
}

func (m *OwnerConfirmReturnment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerConfirmReturnment.Unmarshal(m, b)
}
func (m *OwnerConfirmReturnment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerConfirmReturnment.Marshal(b, m, deterministic)
}
func (m *OwnerConfirmReturnment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerConfirmReturnment.Merge(m, src)
}
func (m *OwnerConfirmReturnment) XXX_Size() int {
	return xxx_messageInfo_OwnerConfirmReturnment.Size(m)
}
func (m *OwnerConfirmReturnment) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerConfirmReturnment.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerConfirmReturnment proto.InternalMessageInfo

func (m *OwnerConfirmReturnment) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerConfirmReturnment) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *OwnerConfirmReturnment) GetOwnerOrderUuid() string {
	if m != nil {
		return m.OwnerOrderUuid
	}
	return ""
}

type TenantReviewOwnerOrder struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	KudakiToken          string   `protobuf:"bytes,2,opt,name=kudaki_token,json=kudakiToken,proto3" json:"kudaki_token,omitempty"`
	OwnerOrderUuid       string   `protobuf:"bytes,3,opt,name=owner_order_uuid,json=ownerOrderUuid,proto3" json:"owner_order_uuid,omitempty"`
	Rating               float64  `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Review               string   `protobuf:"bytes,5,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantReviewOwnerOrder) Reset()         { *m = TenantReviewOwnerOrder{} }
func (m *TenantReviewOwnerOrder) String() string { return proto.CompactTextString(m) }
func (*TenantReviewOwnerOrder) ProtoMessage()    {}
func (*TenantReviewOwnerOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{6}
}

func (m *TenantReviewOwnerOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewOwnerOrder.Unmarshal(m, b)
}
func (m *TenantReviewOwnerOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewOwnerOrder.Marshal(b, m, deterministic)
}
func (m *TenantReviewOwnerOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewOwnerOrder.Merge(m, src)
}
func (m *TenantReviewOwnerOrder) XXX_Size() int {
	return xxx_messageInfo_TenantReviewOwnerOrder.Size(m)
}
func (m *TenantReviewOwnerOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewOwnerOrder.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewOwnerOrder proto.InternalMessageInfo

func (m *TenantReviewOwnerOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewOwnerOrder) GetKudakiToken() string {
	if m != nil {
		return m.KudakiToken
	}
	return ""
}

func (m *TenantReviewOwnerOrder) GetOwnerOrderUuid() string {
	if m != nil {
		return m.OwnerOrderUuid
	}
	return ""
}

func (m *TenantReviewOwnerOrder) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *TenantReviewOwnerOrder) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type OwnersOrderHistoriesRetrieved struct {
	Uid                          string                        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EventStatus                  *Status                       `protobuf:"bytes,2,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RetrieveOwnersOrderHistories *RetrieveOwnersOrderHistories `protobuf:"bytes,3,opt,name=retrieve_owners_order_histories,json=retrieveOwnersOrderHistories,proto3" json:"retrieve_owners_order_histories,omitempty"`
	Result                       []byte                        `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Owner                        *user.User                    `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	XXX_unrecognized             []byte                        `json:"-"`
	XXX_sizecache                int32                         `json:"-"`
}

func (m *OwnersOrderHistoriesRetrieved) Reset()         { *m = OwnersOrderHistoriesRetrieved{} }
func (m *OwnersOrderHistoriesRetrieved) String() string { return proto.CompactTextString(m) }
func (*OwnersOrderHistoriesRetrieved) ProtoMessage()    {}
func (*OwnersOrderHistoriesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{7}
}

func (m *OwnersOrderHistoriesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Unmarshal(m, b)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Marshal(b, m, deterministic)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnersOrderHistoriesRetrieved.Merge(m, src)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_Size() int {
	return xxx_messageInfo_OwnersOrderHistoriesRetrieved.Size(m)
}
func (m *OwnersOrderHistoriesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnersOrderHistoriesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_OwnersOrderHistoriesRetrieved proto.InternalMessageInfo

func (m *OwnersOrderHistoriesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnersOrderHistoriesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetRetrieveOwnersOrderHistories() *RetrieveOwnersOrderHistories {
	if m != nil {
		return m.RetrieveOwnersOrderHistories
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OwnersOrderHistoriesRetrieved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

type TenantOrderHistoriesRetrieved struct {
	Uid                           string                         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant                        *user.User                     `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus                   *Status                        `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	RetrieveTenantsOrderHistories *RetrieveTenantsOrderHistories `protobuf:"bytes,5,opt,name=retrieve_tenants_order_histories,json=retrieveTenantsOrderHistories,proto3" json:"retrieve_tenants_order_histories,omitempty"`
	Result                        []byte                         `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                       `json:"-"`
	XXX_unrecognized              []byte                         `json:"-"`
	XXX_sizecache                 int32                          `json:"-"`
}

func (m *TenantOrderHistoriesRetrieved) Reset()         { *m = TenantOrderHistoriesRetrieved{} }
func (m *TenantOrderHistoriesRetrieved) String() string { return proto.CompactTextString(m) }
func (*TenantOrderHistoriesRetrieved) ProtoMessage()    {}
func (*TenantOrderHistoriesRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{8}
}

func (m *TenantOrderHistoriesRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Unmarshal(m, b)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Marshal(b, m, deterministic)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantOrderHistoriesRetrieved.Merge(m, src)
}
func (m *TenantOrderHistoriesRetrieved) XXX_Size() int {
	return xxx_messageInfo_TenantOrderHistoriesRetrieved.Size(m)
}
func (m *TenantOrderHistoriesRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantOrderHistoriesRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_TenantOrderHistoriesRetrieved proto.InternalMessageInfo

func (m *TenantOrderHistoriesRetrieved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantOrderHistoriesRetrieved) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetRetrieveTenantsOrderHistories() *RetrieveTenantsOrderHistories {
	if m != nil {
		return m.RetrieveTenantsOrderHistories
	}
	return nil
}

func (m *TenantOrderHistoriesRetrieved) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type OwnerOrderApproved struct {
	Uid                  string             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User         `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status            `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrder           *order.OwnerOrder  `protobuf:"bytes,4,opt,name=owner_order,json=ownerOrder,proto3" json:"owner_order,omitempty"`
	ApproveOwnerOrder    *ApproveOwnerOrder `protobuf:"bytes,5,opt,name=approve_owner_order,json=approveOwnerOrder,proto3" json:"approve_owner_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OwnerOrderApproved) Reset()         { *m = OwnerOrderApproved{} }
func (m *OwnerOrderApproved) String() string { return proto.CompactTextString(m) }
func (*OwnerOrderApproved) ProtoMessage()    {}
func (*OwnerOrderApproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{9}
}

func (m *OwnerOrderApproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerOrderApproved.Unmarshal(m, b)
}
func (m *OwnerOrderApproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerOrderApproved.Marshal(b, m, deterministic)
}
func (m *OwnerOrderApproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerOrderApproved.Merge(m, src)
}
func (m *OwnerOrderApproved) XXX_Size() int {
	return xxx_messageInfo_OwnerOrderApproved.Size(m)
}
func (m *OwnerOrderApproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerOrderApproved.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerOrderApproved proto.InternalMessageInfo

func (m *OwnerOrderApproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerOrderApproved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OwnerOrderApproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnerOrderApproved) GetOwnerOrder() *order.OwnerOrder {
	if m != nil {
		return m.OwnerOrder
	}
	return nil
}

func (m *OwnerOrderApproved) GetApproveOwnerOrder() *ApproveOwnerOrder {
	if m != nil {
		return m.ApproveOwnerOrder
	}
	return nil
}

type OwnerOrderDisapproved struct {
	Uid                  string                `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                *user.User            `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus          *Status               `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrder           *order.OwnerOrder     `protobuf:"bytes,4,opt,name=owner_order,json=ownerOrder,proto3" json:"owner_order,omitempty"`
	DisapproveOwnerOrder *DisapproveOwnerOrder `protobuf:"bytes,5,opt,name=disapprove_owner_order,json=disapproveOwnerOrder,proto3" json:"disapprove_owner_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OwnerOrderDisapproved) Reset()         { *m = OwnerOrderDisapproved{} }
func (m *OwnerOrderDisapproved) String() string { return proto.CompactTextString(m) }
func (*OwnerOrderDisapproved) ProtoMessage()    {}
func (*OwnerOrderDisapproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{10}
}

func (m *OwnerOrderDisapproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerOrderDisapproved.Unmarshal(m, b)
}
func (m *OwnerOrderDisapproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerOrderDisapproved.Marshal(b, m, deterministic)
}
func (m *OwnerOrderDisapproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerOrderDisapproved.Merge(m, src)
}
func (m *OwnerOrderDisapproved) XXX_Size() int {
	return xxx_messageInfo_OwnerOrderDisapproved.Size(m)
}
func (m *OwnerOrderDisapproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerOrderDisapproved.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerOrderDisapproved proto.InternalMessageInfo

func (m *OwnerOrderDisapproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerOrderDisapproved) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OwnerOrderDisapproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnerOrderDisapproved) GetOwnerOrder() *order.OwnerOrder {
	if m != nil {
		return m.OwnerOrder
	}
	return nil
}

func (m *OwnerOrderDisapproved) GetDisapproveOwnerOrder() *DisapproveOwnerOrder {
	if m != nil {
		return m.DisapproveOwnerOrder
	}
	return nil
}

type CheckedOut struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	CheckOut             *CheckOut           `protobuf:"bytes,4,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Order                *order.Order        `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	OwnerOrders          []*order.OwnerOrder `protobuf:"bytes,6,rep,name=owner_orders,json=ownerOrders,proto3" json:"owner_orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CheckedOut) Reset()         { *m = CheckedOut{} }
func (m *CheckedOut) String() string { return proto.CompactTextString(m) }
func (*CheckedOut) ProtoMessage()    {}
func (*CheckedOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{11}
}

func (m *CheckedOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckedOut.Unmarshal(m, b)
}
func (m *CheckedOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckedOut.Marshal(b, m, deterministic)
}
func (m *CheckedOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckedOut.Merge(m, src)
}
func (m *CheckedOut) XXX_Size() int {
	return xxx_messageInfo_CheckedOut.Size(m)
}
func (m *CheckedOut) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckedOut.DiscardUnknown(m)
}

var xxx_messageInfo_CheckedOut proto.InternalMessageInfo

func (m *CheckedOut) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CheckedOut) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *CheckedOut) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *CheckedOut) GetCheckOut() *CheckOut {
	if m != nil {
		return m.CheckOut
	}
	return nil
}

func (m *CheckedOut) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *CheckedOut) GetOwnerOrders() []*order.OwnerOrder {
	if m != nil {
		return m.OwnerOrders
	}
	return nil
}

type OrderApproved struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrders          []*order.OwnerOrder `protobuf:"bytes,4,rep,name=owner_orders,json=ownerOrders,proto3" json:"owner_orders,omitempty"`
	Order                *order.Order        `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OrderApproved) Reset()         { *m = OrderApproved{} }
func (m *OrderApproved) String() string { return proto.CompactTextString(m) }
func (*OrderApproved) ProtoMessage()    {}
func (*OrderApproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{12}
}

func (m *OrderApproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderApproved.Unmarshal(m, b)
}
func (m *OrderApproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderApproved.Marshal(b, m, deterministic)
}
func (m *OrderApproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderApproved.Merge(m, src)
}
func (m *OrderApproved) XXX_Size() int {
	return xxx_messageInfo_OrderApproved.Size(m)
}
func (m *OrderApproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderApproved.DiscardUnknown(m)
}

var xxx_messageInfo_OrderApproved proto.InternalMessageInfo

func (m *OrderApproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrderApproved) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *OrderApproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrderApproved) GetOwnerOrders() []*order.OwnerOrder {
	if m != nil {
		return m.OwnerOrders
	}
	return nil
}

func (m *OrderApproved) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderDisapproved struct {
	Uid                  string              `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant               *user.User          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus          *Status             `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrders          []*order.OwnerOrder `protobuf:"bytes,4,rep,name=owner_orders,json=ownerOrders,proto3" json:"owner_orders,omitempty"`
	Order                *order.Order        `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OrderDisapproved) Reset()         { *m = OrderDisapproved{} }
func (m *OrderDisapproved) String() string { return proto.CompactTextString(m) }
func (*OrderDisapproved) ProtoMessage()    {}
func (*OrderDisapproved) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{13}
}

func (m *OrderDisapproved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDisapproved.Unmarshal(m, b)
}
func (m *OrderDisapproved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDisapproved.Marshal(b, m, deterministic)
}
func (m *OrderDisapproved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDisapproved.Merge(m, src)
}
func (m *OrderDisapproved) XXX_Size() int {
	return xxx_messageInfo_OrderDisapproved.Size(m)
}
func (m *OrderDisapproved) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDisapproved.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDisapproved proto.InternalMessageInfo

func (m *OrderDisapproved) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrderDisapproved) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *OrderDisapproved) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OrderDisapproved) GetOwnerOrders() []*order.OwnerOrder {
	if m != nil {
		return m.OwnerOrders
	}
	return nil
}

func (m *OrderDisapproved) GetOrder() *order.Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OwnerConfirmedReturnment struct {
	Uid                    string                  `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Owner                  *user.User              `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	EventStatus            *Status                 `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	OwnerOrder             *order.OwnerOrder       `protobuf:"bytes,4,opt,name=owner_order,json=ownerOrder,proto3" json:"owner_order,omitempty"`
	OwnerConfirmReturnment *OwnerConfirmReturnment `protobuf:"bytes,5,opt,name=owner_confirm_returnment,json=ownerConfirmReturnment,proto3" json:"owner_confirm_returnment,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *OwnerConfirmedReturnment) Reset()         { *m = OwnerConfirmedReturnment{} }
func (m *OwnerConfirmedReturnment) String() string { return proto.CompactTextString(m) }
func (*OwnerConfirmedReturnment) ProtoMessage()    {}
func (*OwnerConfirmedReturnment) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{14}
}

func (m *OwnerConfirmedReturnment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerConfirmedReturnment.Unmarshal(m, b)
}
func (m *OwnerConfirmedReturnment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerConfirmedReturnment.Marshal(b, m, deterministic)
}
func (m *OwnerConfirmedReturnment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerConfirmedReturnment.Merge(m, src)
}
func (m *OwnerConfirmedReturnment) XXX_Size() int {
	return xxx_messageInfo_OwnerConfirmedReturnment.Size(m)
}
func (m *OwnerConfirmedReturnment) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerConfirmedReturnment.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerConfirmedReturnment proto.InternalMessageInfo

func (m *OwnerConfirmedReturnment) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OwnerConfirmedReturnment) GetOwner() *user.User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *OwnerConfirmedReturnment) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *OwnerConfirmedReturnment) GetOwnerOrder() *order.OwnerOrder {
	if m != nil {
		return m.OwnerOrder
	}
	return nil
}

func (m *OwnerConfirmedReturnment) GetOwnerConfirmReturnment() *OwnerConfirmReturnment {
	if m != nil {
		return m.OwnerConfirmReturnment
	}
	return nil
}

type TenantReviewedOwnerOrder struct {
	Uid                    string                  `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tenant                 *user.User              `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	EventStatus            *Status                 `protobuf:"bytes,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	TenantReviewOwnerOrder *TenantReviewOwnerOrder `protobuf:"bytes,4,opt,name=tenant_review_owner_order,json=tenantReviewOwnerOrder,proto3" json:"tenant_review_owner_order,omitempty"`
	OwnerOrderReview       *order.OwnerOrderReview `protobuf:"bytes,5,opt,name=owner_order_review,json=ownerOrderReview,proto3" json:"owner_order_review,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *TenantReviewedOwnerOrder) Reset()         { *m = TenantReviewedOwnerOrder{} }
func (m *TenantReviewedOwnerOrder) String() string { return proto.CompactTextString(m) }
func (*TenantReviewedOwnerOrder) ProtoMessage()    {}
func (*TenantReviewedOwnerOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_8148e438de8b220f, []int{15}
}

func (m *TenantReviewedOwnerOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantReviewedOwnerOrder.Unmarshal(m, b)
}
func (m *TenantReviewedOwnerOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantReviewedOwnerOrder.Marshal(b, m, deterministic)
}
func (m *TenantReviewedOwnerOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantReviewedOwnerOrder.Merge(m, src)
}
func (m *TenantReviewedOwnerOrder) XXX_Size() int {
	return xxx_messageInfo_TenantReviewedOwnerOrder.Size(m)
}
func (m *TenantReviewedOwnerOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantReviewedOwnerOrder.DiscardUnknown(m)
}

var xxx_messageInfo_TenantReviewedOwnerOrder proto.InternalMessageInfo

func (m *TenantReviewedOwnerOrder) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TenantReviewedOwnerOrder) GetTenant() *user.User {
	if m != nil {
		return m.Tenant
	}
	return nil
}

func (m *TenantReviewedOwnerOrder) GetEventStatus() *Status {
	if m != nil {
		return m.EventStatus
	}
	return nil
}

func (m *TenantReviewedOwnerOrder) GetTenantReviewOwnerOrder() *TenantReviewOwnerOrder {
	if m != nil {
		return m.TenantReviewOwnerOrder
	}
	return nil
}

func (m *TenantReviewedOwnerOrder) GetOwnerOrderReview() *order.OwnerOrderReview {
	if m != nil {
		return m.OwnerOrderReview
	}
	return nil
}

func init() {
	proto.RegisterEnum("event.OrderServiceCommandTopic", OrderServiceCommandTopic_name, OrderServiceCommandTopic_value)
	proto.RegisterEnum("event.OrderServiceEventTopic", OrderServiceEventTopic_name, OrderServiceEventTopic_value)
	proto.RegisterType((*RetrieveOwnersOrderHistories)(nil), "event.RetrieveOwnersOrderHistories")
	proto.RegisterType((*RetrieveTenantsOrderHistories)(nil), "event.RetrieveTenantsOrderHistories")
	proto.RegisterType((*ApproveOwnerOrder)(nil), "event.ApproveOwnerOrder")
	proto.RegisterType((*DisapproveOwnerOrder)(nil), "event.DisapproveOwnerOrder")
	proto.RegisterType((*CheckOut)(nil), "event.CheckOut")
	proto.RegisterType((*OwnerConfirmReturnment)(nil), "event.OwnerConfirmReturnment")
	proto.RegisterType((*TenantReviewOwnerOrder)(nil), "event.TenantReviewOwnerOrder")
	proto.RegisterType((*OwnersOrderHistoriesRetrieved)(nil), "event.OwnersOrderHistoriesRetrieved")
	proto.RegisterType((*TenantOrderHistoriesRetrieved)(nil), "event.TenantOrderHistoriesRetrieved")
	proto.RegisterType((*OwnerOrderApproved)(nil), "event.OwnerOrderApproved")
	proto.RegisterType((*OwnerOrderDisapproved)(nil), "event.OwnerOrderDisapproved")
	proto.RegisterType((*CheckedOut)(nil), "event.CheckedOut")
	proto.RegisterType((*OrderApproved)(nil), "event.OrderApproved")
	proto.RegisterType((*OrderDisapproved)(nil), "event.OrderDisapproved")
	proto.RegisterType((*OwnerConfirmedReturnment)(nil), "event.OwnerConfirmedReturnment")
	proto.RegisterType((*TenantReviewedOwnerOrder)(nil), "event.TenantReviewedOwnerOrder")
}

func init() { proto.RegisterFile("events/order.proto", fileDescriptor_8148e438de8b220f) }

var fileDescriptor_8148e438de8b220f = []byte{
	// 1108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x4f, 0x4f, 0xe3, 0x46,
	0x14, 0x5f, 0x9b, 0x4d, 0x4a, 0x5e, 0xc2, 0xae, 0x19, 0x20, 0x78, 0x81, 0x94, 0xac, 0xa1, 0x12,
	0xdd, 0x96, 0x50, 0xd1, 0x6b, 0xff, 0xd1, 0xc4, 0x15, 0x51, 0xb5, 0x09, 0x9d, 0x98, 0xa5, 0xaa,
	0x2a, 0x59, 0x5e, 0x7b, 0x20, 0x2e, 0xd8, 0x46, 0xe3, 0x31, 0x7c, 0x8b, 0x9e, 0x7a, 0xd9, 0x4a,
	0x3d, 0xf5, 0xd0, 0xcf, 0xd0, 0x2f, 0x54, 0xb5, 0xd7, 0x4a, 0xbd, 0x57, 0x9e, 0x19, 0x27, 0x5e,
	0x62, 0xc2, 0x2e, 0x12, 0xab, 0x76, 0x2f, 0x88, 0x79, 0xf3, 0xe6, 0xbd, 0xf7, 0xfb, 0xf9, 0xbd,
	0x9f, 0xc7, 0x01, 0x44, 0x2e, 0x48, 0xc8, 0xe2, 0x9d, 0x88, 0x7a, 0x84, 0xb6, 0xce, 0x69, 0xc4,
	0x22, 0x54, 0xe2, 0xb6, 0x95, 0x35, 0xe7, 0xe4, 0x84, 0x92, 0x13, 0x87, 0x11, 0xb9, 0x9d, 0x77,
	0x5a, 0x59, 0x90, 0x07, 0x63, 0xe6, 0xb0, 0x24, 0x96, 0xc6, 0x95, 0xdc, 0x91, 0x24, 0x26, 0x94,
	0xff, 0x91, 0x7b, 0xc6, 0x64, 0xb8, 0xcb, 0x90, 0x50, 0x3b, 0x1f, 0xf4, 0xfd, 0x69, 0x3e, 0x36,
	0x25, 0x17, 0x3e, 0xb9, 0x14, 0xae, 0xc6, 0x9f, 0x0a, 0xac, 0x61, 0xc2, 0xa8, 0x4f, 0x2e, 0x48,
	0x3f, 0x75, 0x8a, 0xfb, 0xa9, 0xd3, 0xbe, 0x1f, 0xb3, 0x88, 0xfa, 0x24, 0x46, 0x1a, 0xcc, 0x24,
	0xbe, 0xa7, 0x2b, 0x4d, 0x65, 0xab, 0x82, 0xd3, 0x7f, 0xd1, 0x63, 0xa8, 0x9d, 0x26, 0x9e, 0x73,
	0xea, 0xdb, 0x2c, 0x3a, 0x25, 0xa1, 0xae, 0xf2, 0xad, 0xaa, 0xb0, 0x59, 0xa9, 0x09, 0xd5, 0xa1,
	0x1c, 0x1d, 0x1f, 0xc7, 0x84, 0xe9, 0x33, 0x4d, 0x65, 0xab, 0x84, 0xe5, 0x0a, 0x2d, 0x42, 0xe9,
	0xcc, 0x0f, 0x7c, 0xa6, 0xdf, 0xe7, 0x66, 0xb1, 0x40, 0x5f, 0x40, 0x4d, 0x54, 0x26, 0x48, 0xd0,
	0x4b, 0x4d, 0x65, 0xeb, 0xc1, 0x6e, 0xa3, 0x35, 0x46, 0xd1, 0x12, 0xe8, 0x78, 0x69, 0x03, 0xee,
	0x84, 0xab, 0xd1, 0x78, 0x81, 0x36, 0x60, 0x8e, 0x92, 0x38, 0x39, 0x63, 0x76, 0xec, 0x0e, 0x49,
	0xe0, 0xe8, 0xe5, 0xa6, 0xb2, 0x55, 0xc3, 0x35, 0x61, 0x1c, 0x70, 0x9b, 0xf1, 0x97, 0x02, 0x8d,
	0x0c, 0xaa, 0x45, 0x42, 0x27, 0x64, 0x6f, 0x2f, 0x56, 0x0a, 0xf3, 0x7b, 0xe7, 0xe7, 0x34, 0x92,
	0x0f, 0x95, 0x07, 0xbb, 0x1d, 0xbc, 0x2d, 0xd0, 0xf2, 0xcd, 0x93, 0xa4, 0x11, 0x66, 0xb8, 0xdb,
	0x83, 0x68, 0x14, 0xfa, 0x30, 0xf1, 0x3d, 0x23, 0x81, 0xc5, 0x8e, 0x1f, 0x3b, 0x6f, 0x3a, 0xed,
	0xf7, 0x30, 0xdb, 0x1e, 0x12, 0xf7, 0xb4, 0x9f, 0xb0, 0xdb, 0xa5, 0x5a, 0x85, 0x8a, 0xeb, 0x50,
	0x96, 0xcf, 0x31, 0x9b, 0x1a, 0x78, 0xf4, 0x4b, 0xa8, 0x73, 0x28, 0xed, 0x28, 0x3c, 0xf6, 0x69,
	0x80, 0x09, 0x4b, 0x68, 0x18, 0x90, 0x90, 0xdd, 0x35, 0xac, 0xdf, 0x14, 0xa8, 0x8b, 0x2e, 0xc5,
	0x7c, 0x5e, 0xdf, 0x18, 0xa1, 0x69, 0x43, 0x53, 0x87, 0xf9, 0xe1, 0x09, 0xef, 0x5c, 0x05, 0xcb,
	0x15, 0xb7, 0xf3, 0x52, 0x78, 0xd3, 0x56, 0xb0, 0x5c, 0x19, 0x3f, 0xa9, 0xd0, 0x28, 0x92, 0x8e,
	0x6c, 0xd6, 0xbc, 0x82, 0x82, 0x3f, 0x82, 0x1a, 0x17, 0xbe, 0x6c, 0x0c, 0xd2, 0x82, 0xab, 0xbb,
	0x73, 0x2d, 0x6e, 0x6c, 0x65, 0x6d, 0xcf, 0x57, 0xb2, 0xed, 0x7f, 0x80, 0x75, 0x2a, 0x03, 0xda,
	0xbc, 0xe0, 0x58, 0x22, 0x19, 0x66, 0xf9, 0x38, 0x9c, 0xea, 0xee, 0x86, 0x0c, 0x32, 0x4d, 0xd5,
	0xf0, 0x1a, 0x9d, 0xa6, 0x79, 0x1c, 0x69, 0x3a, 0x4d, 0x9c, 0x81, 0x1a, 0x96, 0x2b, 0xf4, 0x01,
	0x94, 0x78, 0x6a, 0x4e, 0x40, 0x75, 0x77, 0x29, 0x3f, 0xb5, 0x5c, 0xa2, 0x0f, 0x63, 0x42, 0xb1,
	0xf0, 0x31, 0x5e, 0xa8, 0xd0, 0x10, 0x0f, 0xf0, 0xd5, 0x69, 0xd9, 0x86, 0x32, 0xe3, 0x47, 0x24,
	0x21, 0xd7, 0x64, 0x90, 0x4e, 0x13, 0x2c, 0xce, 0xdc, 0xc8, 0x62, 0x00, 0xcd, 0x11, 0x8b, 0x22,
	0xc8, 0x24, 0x8d, 0x02, 0xdc, 0xe6, 0x15, 0x1a, 0x0b, 0x15, 0x13, 0x37, 0xe8, 0x54, 0x41, 0xbd,
	0x86, 0x48, 0xe3, 0x47, 0x15, 0xd0, 0xb8, 0xa1, 0xa5, 0x52, 0x15, 0x11, 0x32, 0x62, 0x5c, 0xbd,
	0x99, 0xf1, 0x5b, 0xd0, 0xf1, 0x29, 0x54, 0x73, 0x43, 0xc1, 0x8b, 0xac, 0xee, 0xae, 0x15, 0x88,
	0xf1, 0xa8, 0x56, 0x0c, 0xe3, 0x69, 0x41, 0xfb, 0xb0, 0x20, 0xe5, 0xce, 0xce, 0x87, 0x11, 0x04,
	0xea, 0x32, 0xef, 0x84, 0x0e, 0xe3, 0xf9, 0x09, 0x8d, 0x34, 0x7e, 0x56, 0x61, 0x69, 0xbc, 0x1c,
	0xcb, 0xe8, 0xff, 0x8f, 0x93, 0x6f, 0xa0, 0xee, 0x8d, 0xca, 0x2f, 0xa0, 0x65, 0x55, 0xa6, 0x2e,
	0x7a, 0x55, 0xe0, 0x45, 0xaf, 0xc0, 0x6a, 0xfc, 0xa2, 0x02, 0x70, 0x89, 0x27, 0x5e, 0xb1, 0xc8,
	0xdf, 0xf9, 0xd8, 0x7c, 0x08, 0x15, 0x37, 0x2d, 0xc0, 0x8e, 0x12, 0x26, 0x19, 0x79, 0x28, 0xdd,
	0xb3, 0x77, 0x0f, 0x9e, 0x75, 0xb3, 0xb7, 0xd0, 0x36, 0x94, 0xf2, 0x88, 0x97, 0xaf, 0x79, 0xb9,
	0x63, 0xe1, 0x85, 0x3e, 0x87, 0x5a, 0x8e, 0xa6, 0x58, 0x2f, 0x37, 0x67, 0x6e, 0x64, 0xbc, 0x3a,
	0x66, 0x3c, 0x36, 0xfe, 0x56, 0x60, 0xee, 0xa6, 0x41, 0xba, 0x73, 0x8a, 0xae, 0xa2, 0xb8, 0xff,
	0x9a, 0x28, 0x5e, 0x93, 0x35, 0xe3, 0x1f, 0x05, 0xb4, 0x57, 0x18, 0x96, 0xb7, 0x0e, 0xf7, 0xaf,
	0x2a, 0xe8, 0xf9, 0x1b, 0x09, 0xf1, 0xa6, 0xde, 0x49, 0xfe, 0xdb, 0x62, 0x71, 0x04, 0xba, 0x38,
	0xee, 0x0a, 0x30, 0x36, 0x1d, 0x61, 0x91, 0x74, 0x34, 0x64, 0xf2, 0xe2, 0x4b, 0x18, 0xae, 0x47,
	0x85, 0x76, 0xe3, 0x77, 0x15, 0xf4, 0xfc, 0xed, 0x89, 0x78, 0x53, 0xef, 0x4f, 0x77, 0xde, 0x25,
	0xdf, 0xc2, 0x23, 0x71, 0x56, 0x7e, 0x7d, 0xd9, 0x93, 0xac, 0x65, 0x48, 0x8b, 0x2f, 0x7d, 0xb8,
	0xce, 0x8a, 0x2f, 0x83, 0x07, 0x80, 0x26, 0x3f, 0xee, 0x24, 0x79, 0xc6, 0xd4, 0x07, 0xc1, 0x3d,
	0xb1, 0x16, 0x5d, 0xb1, 0x3c, 0xf9, 0x43, 0x01, 0x5d, 0x7c, 0x7d, 0x10, 0x7a, 0xe1, 0xbb, 0xa4,
	0x1d, 0x05, 0x81, 0x13, 0x7a, 0x56, 0x74, 0xee, 0xbb, 0x68, 0x03, 0xd6, 0xb1, 0x69, 0xe1, 0xae,
	0xf9, 0xcc, 0xb4, 0xfb, 0x47, 0x3d, 0x13, 0x0f, 0xec, 0x3e, 0xee, 0x98, 0xd8, 0xde, 0xef, 0x0e,
	0xac, 0x3e, 0xee, 0x9a, 0x03, 0xed, 0x1e, 0xda, 0x84, 0xe6, 0xc8, 0xc9, 0x32, 0x7b, 0x7b, 0x3d,
	0x6b, 0xd2, 0x4b, 0x41, 0x0d, 0x78, 0x24, 0x36, 0x6d, 0x6c, 0x3e, 0xeb, 0x9a, 0x47, 0x22, 0x9e,
	0x70, 0xd4, 0x54, 0xb4, 0x0c, 0x0b, 0x7b, 0x07, 0x07, 0xb8, 0x9f, 0x25, 0x92, 0x1b, 0x25, 0xb4,
	0x02, 0xf5, 0x4e, 0x77, 0x50, 0xb4, 0x57, 0x46, 0x73, 0x50, 0x69, 0xef, 0x9b, 0xed, 0xaf, 0xed,
	0xfe, 0xa1, 0xa5, 0xbd, 0x83, 0xd6, 0x40, 0x17, 0xfb, 0xed, 0x7e, 0xef, 0xab, 0x2e, 0x7e, 0x6a,
	0x63, 0xd3, 0x3a, 0xc4, 0xbd, 0xa7, 0x66, 0xcf, 0xd2, 0x66, 0x9f, 0xbc, 0x50, 0xa1, 0x9e, 0x07,
	0x6a, 0xa6, 0xfc, 0x0b, 0x98, 0x9b, 0xd0, 0x2c, 0x46, 0x67, 0x67, 0xc0, 0x3a, 0xda, 0x3d, 0xf4,
	0x1e, 0x3c, 0xbe, 0x06, 0x5e, 0xce, 0x4d, 0x41, 0xeb, 0xb0, 0xfa, 0x12, 0x50, 0xb3, 0x73, 0x05,
	0xaa, 0x0e, 0x8b, 0x39, 0x83, 0x2d, 0xa1, 0x75, 0xb4, 0x12, 0x5a, 0x85, 0xe5, 0xfc, 0xce, 0x18,
	0x77, 0x47, 0x2b, 0xa3, 0x87, 0x50, 0xe5, 0x60, 0xd3, 0x78, 0x1c, 0x2e, 0x82, 0x07, 0x57, 0x22,
	0xcc, 0xa2, 0x25, 0x98, 0x9f, 0x3c, 0x5b, 0x41, 0xef, 0xc2, 0xca, 0x4b, 0xcc, 0x98, 0x9d, 0x3c,
	0x37, 0xf0, 0xe5, 0x67, 0xdf, 0x7d, 0x72, 0xe2, 0xb3, 0x61, 0xf2, 0xbc, 0xe5, 0x46, 0xc1, 0x8e,
	0x7f, 0x36, 0x74, 0x82, 0x60, 0xe8, 0x79, 0x3b, 0xe2, 0x93, 0x62, 0x3b, 0x88, 0x92, 0x90, 0x39,
	0x7e, 0xb8, 0x1d, 0x0b, 0xea, 0x76, 0x92, 0x98, 0xb8, 0x4e, 0x4c, 0xe2, 0x1d, 0xf1, 0x7b, 0xc6,
	0xf3, 0x32, 0xff, 0x79, 0xe1, 0xe3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xd2, 0x71, 0x3b,
	0x19, 0x11, 0x00, 0x00,
}
