settings:
  recovery:
    index: true
    events: false
    tools: false
  legacy:
    force: false
    interval: 0ms
schema:
- name: kudaki-user-info-service
  path: .
  commands:
    clean:
      status: true
    run:
      status: true
  args:
    - -- KAFKA_VERSION 2.1.1
    - -- KAFKA_BROKERS 178.62.107.160:29092
    - -- QUERY_DB_PATH tcp(178.62.107.160:3307)
    - -- QUERY_DB_USERNAME root
    - -- QUERY_DB_PASSWORD mysqlreplicarocks
    - -- QUERY_DB_NAME kudaki_user
    - -- DB_PATH tcp(178.62.107.160:3306)
    - -- DB_USERNAME kudaki_user_repo
    - -- DB_PASSWORD kudakiuserreporocks
    - -- DB_NAME kudaki_user
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths: 
    - .git
    - .realize
    - vendor
    - .vendor-new
    scripts:
    - type: before
      command: taskkill /IM "kudaki-user-info-service.exe" /F